/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "A5Param.h"

asn_TYPE_member_t asn_MBR_A5Param_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct A5Param, a5_Threshold1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"a5-Threshold1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct A5Param, a5_Threshold2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"a5-Threshold2"
		},
};
static const ber_tlv_tag_t asn_DEF_A5Param_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_A5Param_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* a5-Threshold1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* a5-Threshold2 */
};
asn_SEQUENCE_specifics_t asn_SPC_A5Param_specs_1 = {
	sizeof(struct A5Param),
	offsetof(struct A5Param, _asn_ctx),
	asn_MAP_A5Param_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_A5Param = {
	"A5Param",
	"A5Param",
	&asn_OP_SEQUENCE,
	asn_DEF_A5Param_tags_1,
	sizeof(asn_DEF_A5Param_tags_1)
		/sizeof(asn_DEF_A5Param_tags_1[0]), /* 1 */
	asn_DEF_A5Param_tags_1,	/* Same as above */
	sizeof(asn_DEF_A5Param_tags_1)
		/sizeof(asn_DEF_A5Param_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_A5Param_1,
	2,	/* Elements count */
	&asn_SPC_A5Param_specs_1	/* Additional specs */
};

