/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_AdmEstCause_H_
#define	_AdmEstCause_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdmEstCause {
	AdmEstCause_emergency	= 0,
	AdmEstCause_highp_access	= 1,
	AdmEstCause_mt_access	= 2,
	AdmEstCause_mo_signalling	= 3,
	AdmEstCause_mo_data	= 4
	/*
	 * Enumeration is extensible
	 */
} e_AdmEstCause;

/* AdmEstCause */
typedef long	 AdmEstCause_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AdmEstCause_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AdmEstCause;
extern const asn_INTEGER_specifics_t asn_SPC_AdmEstCause_specs_1;
asn_struct_free_f AdmEstCause_free;
asn_struct_print_f AdmEstCause_print;
asn_constr_check_f AdmEstCause_constraint;
ber_type_decoder_f AdmEstCause_decode_ber;
der_type_encoder_f AdmEstCause_encode_der;
xer_type_decoder_f AdmEstCause_decode_xer;
xer_type_encoder_f AdmEstCause_encode_xer;
oer_type_decoder_f AdmEstCause_decode_oer;
oer_type_encoder_f AdmEstCause_encode_oer;
per_type_decoder_f AdmEstCause_decode_uper;
per_type_encoder_f AdmEstCause_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdmEstCause_H_ */
#include <asn_internal.h>
