/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "AdmEstCause.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_AdmEstCause_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_AdmEstCause_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_AdmEstCause_value2enum_1[] = {
	{ 0,	9,	"emergency" },
	{ 1,	12,	"highp-access" },
	{ 2,	9,	"mt-access" },
	{ 3,	13,	"mo-signalling" },
	{ 4,	7,	"mo-data" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_AdmEstCause_enum2value_1[] = {
	0,	/* emergency(0) */
	1,	/* highp-access(1) */
	4,	/* mo-data(4) */
	3,	/* mo-signalling(3) */
	2	/* mt-access(2) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_AdmEstCause_specs_1 = {
	asn_MAP_AdmEstCause_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_AdmEstCause_enum2value_1,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	6,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_AdmEstCause_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_AdmEstCause = {
	"AdmEstCause",
	"AdmEstCause",
	&asn_OP_NativeEnumerated,
	asn_DEF_AdmEstCause_tags_1,
	sizeof(asn_DEF_AdmEstCause_tags_1)
		/sizeof(asn_DEF_AdmEstCause_tags_1[0]), /* 1 */
	asn_DEF_AdmEstCause_tags_1,	/* Same as above */
	sizeof(asn_DEF_AdmEstCause_tags_1)
		/sizeof(asn_DEF_AdmEstCause_tags_1[0]), /* 1 */
	{ &asn_OER_type_AdmEstCause_constr_1, &asn_PER_type_AdmEstCause_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_AdmEstCause_specs_1	/* Additional specs */
};

