/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ARFCN_Value_H_
#define	_ARFCN_Value_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ARFCN-Value */
typedef long	 ARFCN_Value_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ARFCN_Value_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ARFCN_Value;
asn_struct_free_f ARFCN_Value_free;
asn_struct_print_f ARFCN_Value_print;
asn_constr_check_f ARFCN_Value_constraint;
ber_type_decoder_f ARFCN_Value_decode_ber;
der_type_encoder_f ARFCN_Value_encode_der;
xer_type_decoder_f ARFCN_Value_decode_xer;
xer_type_encoder_f ARFCN_Value_encode_xer;
oer_type_decoder_f ARFCN_Value_decode_oer;
oer_type_encoder_f ARFCN_Value_encode_oer;
per_type_decoder_f ARFCN_Value_decode_uper;
per_type_encoder_f ARFCN_Value_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ARFCN_Value_H_ */
#include <asn_internal.h>
