/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "BearerAdmissionRequest.h"

static int
memb_num_erabs_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 11)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_num_erabs_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (1..11) */,
	-1};
static asn_per_constraints_t asn_PER_memb_num_erabs_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  11 }	/* (1..11) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_BearerAdmissionRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BearerAdmissionRequest, crnti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BearerAdmissionRequest, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BearerAdmissionRequest, ue_ambr),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEAMBR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-ambr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BearerAdmissionRequest, num_erabs),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_num_erabs_constr_5, &asn_PER_memb_num_erabs_constr_5,  memb_num_erabs_constraint_1 },
		0, 0, /* No default value */
		"num-erabs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BearerAdmissionRequest, erab_params),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ERABParams,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"erab-params"
		},
};
static const ber_tlv_tag_t asn_DEF_BearerAdmissionRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BearerAdmissionRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ue-ambr */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* num-erabs */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* erab-params */
};
asn_SEQUENCE_specifics_t asn_SPC_BearerAdmissionRequest_specs_1 = {
	sizeof(struct BearerAdmissionRequest),
	offsetof(struct BearerAdmissionRequest, _asn_ctx),
	asn_MAP_BearerAdmissionRequest_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BearerAdmissionRequest = {
	"BearerAdmissionRequest",
	"BearerAdmissionRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_BearerAdmissionRequest_tags_1,
	sizeof(asn_DEF_BearerAdmissionRequest_tags_1)
		/sizeof(asn_DEF_BearerAdmissionRequest_tags_1[0]), /* 1 */
	asn_DEF_BearerAdmissionRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_BearerAdmissionRequest_tags_1)
		/sizeof(asn_DEF_BearerAdmissionRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BearerAdmissionRequest_1,
	5,	/* Elements count */
	&asn_SPC_BearerAdmissionRequest_specs_1	/* Additional specs */
};

