/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "BearerReleaseInd.h"

static int
memb_num_erabs_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 11)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_erab_ids_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 11)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_erab_ids_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..11)) */};
static asn_per_constraints_t asn_PER_type_erab_ids_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  11 }	/* (SIZE(1..11)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_num_erabs_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (1..11) */,
	-1};
static asn_per_constraints_t asn_PER_memb_num_erabs_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  11 }	/* (1..11) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_erab_ids_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..11)) */};
static asn_per_constraints_t asn_PER_memb_erab_ids_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  11 }	/* (SIZE(1..11)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_erab_ids_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_ERAB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_erab_ids_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_erab_ids_specs_5 = {
	sizeof(struct BearerReleaseInd__erab_ids),
	offsetof(struct BearerReleaseInd__erab_ids, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_erab_ids_5 = {
	"erab-ids",
	"erab-ids",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_erab_ids_tags_5,
	sizeof(asn_DEF_erab_ids_tags_5)
		/sizeof(asn_DEF_erab_ids_tags_5[0]) - 1, /* 1 */
	asn_DEF_erab_ids_tags_5,	/* Same as above */
	sizeof(asn_DEF_erab_ids_tags_5)
		/sizeof(asn_DEF_erab_ids_tags_5[0]), /* 2 */
	{ &asn_OER_type_erab_ids_constr_5, &asn_PER_type_erab_ids_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_erab_ids_5,
	1,	/* Single element */
	&asn_SPC_erab_ids_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_BearerReleaseInd_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BearerReleaseInd, crnti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BearerReleaseInd, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BearerReleaseInd, num_erabs),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_num_erabs_constr_4, &asn_PER_memb_num_erabs_constr_4,  memb_num_erabs_constraint_1 },
		0, 0, /* No default value */
		"num-erabs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BearerReleaseInd, erab_ids),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_erab_ids_5,
		0,
		{ &asn_OER_memb_erab_ids_constr_5, &asn_PER_memb_erab_ids_constr_5,  memb_erab_ids_constraint_1 },
		0, 0, /* No default value */
		"erab-ids"
		},
};
static const ber_tlv_tag_t asn_DEF_BearerReleaseInd_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BearerReleaseInd_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* num-erabs */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* erab-ids */
};
asn_SEQUENCE_specifics_t asn_SPC_BearerReleaseInd_specs_1 = {
	sizeof(struct BearerReleaseInd),
	offsetof(struct BearerReleaseInd, _asn_ctx),
	asn_MAP_BearerReleaseInd_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BearerReleaseInd = {
	"BearerReleaseInd",
	"BearerReleaseInd",
	&asn_OP_SEQUENCE,
	asn_DEF_BearerReleaseInd_tags_1,
	sizeof(asn_DEF_BearerReleaseInd_tags_1)
		/sizeof(asn_DEF_BearerReleaseInd_tags_1[0]), /* 1 */
	asn_DEF_BearerReleaseInd_tags_1,	/* Same as above */
	sizeof(asn_DEF_BearerReleaseInd_tags_1)
		/sizeof(asn_DEF_BearerReleaseInd_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BearerReleaseInd_1,
	4,	/* Elements count */
	&asn_SPC_BearerReleaseInd_specs_1	/* Additional specs */
};

