/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "CACap.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_caclassdl_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_caclassdl_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_caclassul_constr_11 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_caclassul_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_caclassdl_value2enum_3[] = {
	{ 0,	1,	"a" },
	{ 1,	1,	"b" },
	{ 2,	1,	"c" },
	{ 3,	1,	"d" },
	{ 4,	1,	"e" },
	{ 5,	1,	"f" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_caclassdl_enum2value_3[] = {
	0,	/* a(0) */
	1,	/* b(1) */
	2,	/* c(2) */
	3,	/* d(3) */
	4,	/* e(4) */
	5	/* f(5) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_caclassdl_specs_3 = {
	asn_MAP_caclassdl_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_caclassdl_enum2value_3,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	7,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_caclassdl_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_caclassdl_3 = {
	"caclassdl",
	"caclassdl",
	&asn_OP_NativeEnumerated,
	asn_DEF_caclassdl_tags_3,
	sizeof(asn_DEF_caclassdl_tags_3)
		/sizeof(asn_DEF_caclassdl_tags_3[0]) - 1, /* 1 */
	asn_DEF_caclassdl_tags_3,	/* Same as above */
	sizeof(asn_DEF_caclassdl_tags_3)
		/sizeof(asn_DEF_caclassdl_tags_3[0]), /* 2 */
	{ &asn_OER_type_caclassdl_constr_3, &asn_PER_type_caclassdl_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_caclassdl_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_caclassul_value2enum_11[] = {
	{ 0,	1,	"a" },
	{ 1,	1,	"b" },
	{ 2,	1,	"c" },
	{ 3,	1,	"d" },
	{ 4,	1,	"e" },
	{ 5,	1,	"f" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_caclassul_enum2value_11[] = {
	0,	/* a(0) */
	1,	/* b(1) */
	2,	/* c(2) */
	3,	/* d(3) */
	4,	/* e(4) */
	5	/* f(5) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_caclassul_specs_11 = {
	asn_MAP_caclassul_value2enum_11,	/* "tag" => N; sorted by tag */
	asn_MAP_caclassul_enum2value_11,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	7,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_caclassul_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_caclassul_11 = {
	"caclassul",
	"caclassul",
	&asn_OP_NativeEnumerated,
	asn_DEF_caclassul_tags_11,
	sizeof(asn_DEF_caclassul_tags_11)
		/sizeof(asn_DEF_caclassul_tags_11[0]) - 1, /* 1 */
	asn_DEF_caclassul_tags_11,	/* Same as above */
	sizeof(asn_DEF_caclassul_tags_11)
		/sizeof(asn_DEF_caclassul_tags_11[0]), /* 2 */
	{ &asn_OER_type_caclassul_constr_11, &asn_PER_type_caclassul_constr_11, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_caclassul_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CACap_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CACap, band),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"band"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CACap, caclassdl),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_caclassdl_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"caclassdl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CACap, caclassul),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_caclassul_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"caclassul"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CACap, crossCarrierSched),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crossCarrierSched"
		},
};
static const ber_tlv_tag_t asn_DEF_CACap_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CACap_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* band */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* caclassdl */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* caclassul */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* crossCarrierSched */
};
asn_SEQUENCE_specifics_t asn_SPC_CACap_specs_1 = {
	sizeof(struct CACap),
	offsetof(struct CACap, _asn_ctx),
	asn_MAP_CACap_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CACap = {
	"CACap",
	"CACap",
	&asn_OP_SEQUENCE,
	asn_DEF_CACap_tags_1,
	sizeof(asn_DEF_CACap_tags_1)
		/sizeof(asn_DEF_CACap_tags_1[0]), /* 1 */
	asn_DEF_CACap_tags_1,	/* Same as above */
	sizeof(asn_DEF_CACap_tags_1)
		/sizeof(asn_DEF_CACap_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CACap_1,
	4,	/* Elements count */
	&asn_SPC_CACap_specs_1	/* Additional specs */
};

