/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_CACap_H_
#define	_CACap_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CACap__caclassdl {
	CACap__caclassdl_a	= 0,
	CACap__caclassdl_b	= 1,
	CACap__caclassdl_c	= 2,
	CACap__caclassdl_d	= 3,
	CACap__caclassdl_e	= 4,
	CACap__caclassdl_f	= 5
	/*
	 * Enumeration is extensible
	 */
} e_CACap__caclassdl;
typedef enum CACap__caclassul {
	CACap__caclassul_a	= 0,
	CACap__caclassul_b	= 1,
	CACap__caclassul_c	= 2,
	CACap__caclassul_d	= 3,
	CACap__caclassul_e	= 4,
	CACap__caclassul_f	= 5
	/*
	 * Enumeration is extensible
	 */
} e_CACap__caclassul;

/* CACap */
typedef struct CACap {
	long	 band;
	long	 caclassdl;
	long	 caclassul;
	BOOLEAN_t	 crossCarrierSched;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CACap_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_caclassdl_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_caclassul_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CACap;
extern asn_SEQUENCE_specifics_t asn_SPC_CACap_specs_1;
extern asn_TYPE_member_t asn_MBR_CACap_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _CACap_H_ */
#include <asn_internal.h>
