/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "CellConfigReport.h"

static int
memb_tdd_config_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_tdd_spl_sf_config_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_tdd_config_constr_12 CC_NOTUSED = {
	{ 1, 1 }	/* (0..6) */,
	-1};
static asn_per_constraints_t asn_PER_memb_tdd_config_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_tdd_spl_sf_config_constr_13 CC_NOTUSED = {
	{ 1, 1 }	/* (0..8) */,
	-1};
static asn_per_constraints_t asn_PER_memb_tdd_spl_sf_config_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  8 }	/* (0..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_cand_scells_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CandScell,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_cand_scells_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_cand_scells_specs_4 = {
	sizeof(struct CellConfigReport__cand_scells),
	offsetof(struct CellConfigReport__cand_scells, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cand_scells_4 = {
	"cand-scells",
	"cand-scells",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_cand_scells_tags_4,
	sizeof(asn_DEF_cand_scells_tags_4)
		/sizeof(asn_DEF_cand_scells_tags_4[0]) - 1, /* 1 */
	asn_DEF_cand_scells_tags_4,	/* Same as above */
	sizeof(asn_DEF_cand_scells_tags_4)
		/sizeof(asn_DEF_cand_scells_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_cand_scells_4,
	1,	/* Single element */
	&asn_SPC_cand_scells_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CellConfigReport_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, pci),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pci"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, cand_scells),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_cand_scells_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cand-scells"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, earfcn_dl),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_Value,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"earfcn-dl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, earfcn_ul),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_Value,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"earfcn-ul"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, rbs_per_tti_dl),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rbs-per-tti-dl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, rbs_per_tti_ul),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rbs-per-tti-ul"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, num_tx_antenna),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"num-tx-antenna"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, duplex_mode),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DuplexMode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"duplex-mode"
		},
	{ ATF_POINTER, 2, offsetof(struct CellConfigReport, tdd_config),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_tdd_config_constr_12, &asn_PER_memb_tdd_config_constr_12,  memb_tdd_config_constraint_1 },
		0, 0, /* No default value */
		"tdd-config"
		},
	{ ATF_POINTER, 1, offsetof(struct CellConfigReport, tdd_spl_sf_config),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_tdd_spl_sf_config_constr_13, &asn_PER_memb_tdd_spl_sf_config_constr_13,  memb_tdd_spl_sf_config_constraint_1 },
		0, 0, /* No default value */
		"tdd-spl-sf-config"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, max_num_connected_ues),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"max-num-connected-ues"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, max_num_connected_bearers),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"max-num-connected-bearers"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, max_num_ues_sched_per_tti_dl),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"max-num-ues-sched-per-tti-dl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, max_num_ues_sched_per_tti_ul),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"max-num-ues-sched-per-tti-ul"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CellConfigReport, dlfs_sched_enable),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dlfs-sched-enable"
		},
	{ ATF_POINTER, 1, offsetof(struct CellConfigReport, featureSupportList),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"featureSupportList"
		},
};
static const int asn_MAP_CellConfigReport_oms_1[] = { 9, 10, 16 };
static const ber_tlv_tag_t asn_DEF_CellConfigReport_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CellConfigReport_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pci */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cand-scells */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* earfcn-dl */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* earfcn-ul */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* rbs-per-tti-dl */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* rbs-per-tti-ul */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* num-tx-antenna */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* duplex-mode */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* tdd-config */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* tdd-spl-sf-config */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* max-num-connected-ues */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* max-num-connected-bearers */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* max-num-ues-sched-per-tti-dl */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* max-num-ues-sched-per-tti-ul */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* dlfs-sched-enable */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 } /* featureSupportList */
};
asn_SEQUENCE_specifics_t asn_SPC_CellConfigReport_specs_1 = {
	sizeof(struct CellConfigReport),
	offsetof(struct CellConfigReport, _asn_ctx),
	asn_MAP_CellConfigReport_tag2el_1,
	17,	/* Count of tags in the map */
	asn_MAP_CellConfigReport_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	17,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CellConfigReport = {
	"CellConfigReport",
	"CellConfigReport",
	&asn_OP_SEQUENCE,
	asn_DEF_CellConfigReport_tags_1,
	sizeof(asn_DEF_CellConfigReport_tags_1)
		/sizeof(asn_DEF_CellConfigReport_tags_1[0]), /* 1 */
	asn_DEF_CellConfigReport_tags_1,	/* Same as above */
	sizeof(asn_DEF_CellConfigReport_tags_1)
		/sizeof(asn_DEF_CellConfigReport_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CellConfigReport_1,
	17,	/* Elements count */
	&asn_SPC_CellConfigReport_specs_1	/* Additional specs */
};

