/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_DCCap_H_
#define	_DCCap_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DCCap__drb_TypeSplit {
	DCCap__drb_TypeSplit_supported	= 0
} e_DCCap__drb_TypeSplit;

/* DCCap */
typedef struct DCCap {
	long	 drb_TypeSplit;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DCCap_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_drb_TypeSplit_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DCCap;
extern asn_SEQUENCE_specifics_t asn_SPC_DCCap_specs_1;
extern asn_TYPE_member_t asn_MBR_DCCap_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _DCCap_H_ */
#include <asn_internal.h>
