/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ECGI_H_
#define	_ECGI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-Identity.h"
#include "EUTRANCellIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ECGI */
typedef struct ECGI {
	PLMN_Identity_t	 pLMN_Identity;
	EUTRANCellIdentifier_t	 eUTRANcellIdentifier;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ECGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECGI;
extern asn_SEQUENCE_specifics_t asn_SPC_ECGI_specs_1;
extern asn_TYPE_member_t asn_MBR_ECGI_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ECGI_H_ */
#include <asn_internal.h>
