/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ERAB_ID_H_
#define	_ERAB_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ERAB-ID */
typedef long	 ERAB_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ERAB_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ERAB_ID;
asn_struct_free_f ERAB_ID_free;
asn_struct_print_f ERAB_ID_print;
asn_constr_check_f ERAB_ID_constraint;
ber_type_decoder_f ERAB_ID_decode_ber;
der_type_encoder_f ERAB_ID_encode_der;
xer_type_decoder_f ERAB_ID_decode_xer;
xer_type_encoder_f ERAB_ID_encode_xer;
oer_type_decoder_f ERAB_ID_decode_oer;
oer_type_encoder_f ERAB_ID_encode_oer;
per_type_decoder_f ERAB_ID_decode_uper;
per_type_encoder_f ERAB_ID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ERAB_ID_H_ */
#include <asn_internal.h>
