/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ERABParams_Item_H_
#define	_ERABParams_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ERAB-ID.h"
#include "ERABDirection.h"
#include "ERABType.h"
#include "QCI.h"
#include <NativeInteger.h>
#include "BitRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ERABParams-Item */
typedef struct ERABParams_Item {
	ERAB_ID_t	 id;
	ERABDirection_t	 direction;
	ERABType_t	 type;
	QCI_t	 qci;
	long	 arp;
	BitRate_t	 gbr_dl;
	BitRate_t	 gbr_ul;
	BitRate_t	 mbr_dl;
	BitRate_t	 mbr_ul;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ERABParams_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ERABParams_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_ERABParams_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_ERABParams_Item_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _ERABParams_Item_H_ */
#include <asn_internal.h>
