/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "ERABResponse-Item.h"

asn_TYPE_member_t asn_MBR_ERABResponse_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ERABResponse_Item, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ERAB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ERABResponse_Item, decision),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ERABDecision,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"decision"
		},
};
static const ber_tlv_tag_t asn_DEF_ERABResponse_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ERABResponse_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* decision */
};
asn_SEQUENCE_specifics_t asn_SPC_ERABResponse_Item_specs_1 = {
	sizeof(struct ERABResponse_Item),
	offsetof(struct ERABResponse_Item, _asn_ctx),
	asn_MAP_ERABResponse_Item_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ERABResponse_Item = {
	"ERABResponse-Item",
	"ERABResponse-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_ERABResponse_Item_tags_1,
	sizeof(asn_DEF_ERABResponse_Item_tags_1)
		/sizeof(asn_DEF_ERABResponse_Item_tags_1[0]), /* 1 */
	asn_DEF_ERABResponse_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ERABResponse_Item_tags_1)
		/sizeof(asn_DEF_ERABResponse_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ERABResponse_Item_1,
	2,	/* Elements count */
	&asn_SPC_ERABResponse_Item_specs_1	/* Additional specs */
};

