/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ERABType_H_
#define	_ERABType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ERABType {
	ERABType_default	= 0,
	ERABType_dedicated	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ERABType;

/* ERABType */
typedef long	 ERABType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ERABType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ERABType;
extern const asn_INTEGER_specifics_t asn_SPC_ERABType_specs_1;
asn_struct_free_f ERABType_free;
asn_struct_print_f ERABType_print;
asn_constr_check_f ERABType_constraint;
ber_type_decoder_f ERABType_decode_ber;
der_type_encoder_f ERABType_encode_der;
xer_type_decoder_f ERABType_decode_xer;
xer_type_encoder_f ERABType_encode_xer;
oer_type_decoder_f ERABType_decode_oer;
oer_type_encoder_f ERABType_encode_oer;
per_type_decoder_f ERABType_decode_uper;
per_type_encoder_f ERABType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ERABType_H_ */
#include <asn_internal.h>
