/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "ERABParams-Item.h"

asn_TYPE_member_t asn_MBR_ERABParams_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ERABParams_Item, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ERAB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ERABParams_Item, direction),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ERABDirection,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"direction"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ERABParams_Item, type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ERABType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ERABParams_Item, qci),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QCI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qci"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ERABParams_Item, arp),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"arp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ERABParams_Item, gbr_dl),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gbr-dl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ERABParams_Item, gbr_ul),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gbr-ul"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ERABParams_Item, mbr_dl),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbr-dl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ERABParams_Item, mbr_ul),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mbr-ul"
		},
};
static const ber_tlv_tag_t asn_DEF_ERABParams_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ERABParams_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* direction */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* type */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* qci */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* arp */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* gbr-dl */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* gbr-ul */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* mbr-dl */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* mbr-ul */
};
asn_SEQUENCE_specifics_t asn_SPC_ERABParams_Item_specs_1 = {
	sizeof(struct ERABParams_Item),
	offsetof(struct ERABParams_Item, _asn_ctx),
	asn_MAP_ERABParams_Item_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	9,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ERABParams_Item = {
	"ERABParams-Item",
	"ERABParams-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_ERABParams_Item_tags_1,
	sizeof(asn_DEF_ERABParams_Item_tags_1)
		/sizeof(asn_DEF_ERABParams_Item_tags_1[0]), /* 1 */
	asn_DEF_ERABParams_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_ERABParams_Item_tags_1)
		/sizeof(asn_DEF_ERABParams_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ERABParams_Item_1,
	9,	/* Elements count */
	&asn_SPC_ERABParams_Item_specs_1	/* Additional specs */
};

