/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ERABDecision_H_
#define	_ERABDecision_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ERABDecision {
	ERABDecision_success	= 0,
	ERABDecision_failure	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ERABDecision;

/* ERABDecision */
typedef long	 ERABDecision_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ERABDecision_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ERABDecision;
extern const asn_INTEGER_specifics_t asn_SPC_ERABDecision_specs_1;
asn_struct_free_f ERABDecision_free;
asn_struct_print_f ERABDecision_print;
asn_constr_check_f ERABDecision_constraint;
ber_type_decoder_f ERABDecision_decode_ber;
der_type_encoder_f ERABDecision_encode_der;
xer_type_decoder_f ERABDecision_decode_xer;
xer_type_encoder_f ERABDecision_encode_xer;
oer_type_decoder_f ERABDecision_decode_oer;
oer_type_encoder_f ERABDecision_encode_oer;
per_type_decoder_f ERABDecision_decode_uper;
per_type_encoder_f ERABDecision_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ERABDecision_H_ */
#include <asn_internal.h>
