/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ERABResponse_Item_H_
#define	_ERABResponse_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ERAB-ID.h"
#include "ERABDecision.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ERABResponse-Item */
typedef struct ERABResponse_Item {
	ERAB_ID_t	 id;
	ERABDecision_t	 decision;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ERABResponse_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ERABResponse_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_ERABResponse_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_ERABResponse_Item_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ERABResponse_Item_H_ */
#include <asn_internal.h>
