/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ERABDirection_H_
#define	_ERABDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ERABDirection {
	ERABDirection_dl	= 0,
	ERABDirection_ul	= 1,
	ERABDirection_both	= 2
	/*
	 * Enumeration is extensible
	 */
} e_ERABDirection;

/* ERABDirection */
typedef long	 ERABDirection_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ERABDirection_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ERABDirection;
extern const asn_INTEGER_specifics_t asn_SPC_ERABDirection_specs_1;
asn_struct_free_f ERABDirection_free;
asn_struct_print_f ERABDirection_print;
asn_constr_check_f ERABDirection_constraint;
ber_type_decoder_f ERABDirection_decode_ber;
der_type_encoder_f ERABDirection_encode_der;
xer_type_decoder_f ERABDirection_decode_xer;
xer_type_encoder_f ERABDirection_encode_xer;
oer_type_decoder_f ERABDirection_decode_oer;
oer_type_encoder_f ERABDirection_encode_oer;
per_type_decoder_f ERABDirection_decode_uper;
per_type_encoder_f ERABDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ERABDirection_H_ */
#include <asn_internal.h>
