/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ERABParams_H_
#define	_ERABParams_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ERABParams_Item;

/* ERABParams */
typedef struct ERABParams {
	A_SEQUENCE_OF(struct ERABParams_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ERABParams_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ERABParams;
extern asn_SET_OF_specifics_t asn_SPC_ERABParams_specs_1;
extern asn_TYPE_member_t asn_MBR_ERABParams_1[1];
extern asn_per_constraints_t asn_PER_type_ERABParams_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ERABParams-Item.h"

#endif	/* _ERABParams_H_ */
#include <asn_internal.h>
