/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "HOCause.h"

static asn_TYPE_member_t asn_MBR_ho_trigger_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RXSigReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ho_trigger_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ho_trigger_specs_6 = {
	sizeof(struct HOCause__ho_trigger),
	offsetof(struct HOCause__ho_trigger, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ho_trigger_6 = {
	"ho-trigger",
	"ho-trigger",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ho_trigger_tags_6,
	sizeof(asn_DEF_ho_trigger_tags_6)
		/sizeof(asn_DEF_ho_trigger_tags_6[0]) - 1, /* 1 */
	asn_DEF_ho_trigger_tags_6,	/* Same as above */
	sizeof(asn_DEF_ho_trigger_tags_6)
		/sizeof(asn_DEF_ho_trigger_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_ho_trigger_6,
	1,	/* Single element */
	&asn_SPC_ho_trigger_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_HOCause_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HOCause, crnti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HOCause, ecgi_s),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi-s"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HOCause, ecgi_t),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi-t"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HOCause, ho_cause),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ho-cause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HOCause, ho_trigger),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ho_trigger_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ho-trigger"
		},
};
static const ber_tlv_tag_t asn_DEF_HOCause_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_HOCause_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ecgi-s */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ecgi-t */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ho-cause */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ho-trigger */
};
asn_SEQUENCE_specifics_t asn_SPC_HOCause_specs_1 = {
	sizeof(struct HOCause),
	offsetof(struct HOCause, _asn_ctx),
	asn_MAP_HOCause_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_HOCause = {
	"HOCause",
	"HOCause",
	&asn_OP_SEQUENCE,
	asn_DEF_HOCause_tags_1,
	sizeof(asn_DEF_HOCause_tags_1)
		/sizeof(asn_DEF_HOCause_tags_1[0]), /* 1 */
	asn_DEF_HOCause_tags_1,	/* Same as above */
	sizeof(asn_DEF_HOCause_tags_1)
		/sizeof(asn_DEF_HOCause_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_HOCause_1,
	5,	/* Elements count */
	&asn_SPC_HOCause_specs_1	/* Additional specs */
};

