/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_HOCause_H_
#define	_HOCause_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CRNTI.h"
#include "ECGI.h"
#include <BIT_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RXSigReport;

/* HOCause */
typedef struct HOCause {
	CRNTI_t	 crnti;
	ECGI_t	 ecgi_s;
	ECGI_t	 ecgi_t;
	BIT_STRING_t	 ho_cause;
	struct HOCause__ho_trigger {
		A_SEQUENCE_OF(struct RXSigReport) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ho_trigger;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HOCause_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HOCause;
extern asn_SEQUENCE_specifics_t asn_SPC_HOCause_specs_1;
extern asn_TYPE_member_t asn_MBR_HOCause_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RXSigReport.h"

#endif	/* _HOCause_H_ */
#include <asn_internal.h>
