/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_HOComplete_H_
#define	_HOComplete_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "CRNTI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HOComplete */
typedef struct HOComplete {
	ECGI_t	 ecgi_t;
	ECGI_t	 ecgi_s;
	CRNTI_t	 crnti_new;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HOComplete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HOComplete;
extern asn_SEQUENCE_specifics_t asn_SPC_HOComplete_specs_1;
extern asn_TYPE_member_t asn_MBR_HOComplete_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _HOComplete_H_ */
#include <asn_internal.h>
