/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_HOFailureCause_H_
#define	_HOFailureCause_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HOFailureCause {
	HOFailureCause_other	= 0
	/*
	 * Enumeration is extensible
	 */
} e_HOFailureCause;

/* HOFailureCause */
typedef long	 HOFailureCause_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HOFailureCause_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HOFailureCause;
extern const asn_INTEGER_specifics_t asn_SPC_HOFailureCause_specs_1;
asn_struct_free_f HOFailureCause_free;
asn_struct_print_f HOFailureCause_print;
asn_constr_check_f HOFailureCause_constraint;
ber_type_decoder_f HOFailureCause_decode_ber;
der_type_encoder_f HOFailureCause_encode_der;
xer_type_decoder_f HOFailureCause_decode_xer;
xer_type_encoder_f HOFailureCause_encode_xer;
oer_type_decoder_f HOFailureCause_decode_oer;
oer_type_encoder_f HOFailureCause_encode_oer;
per_type_decoder_f HOFailureCause_decode_uper;
per_type_encoder_f HOFailureCause_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HOFailureCause_H_ */
#include <asn_internal.h>
