/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "L2MeasConfig.h"

static asn_TYPE_member_t asn_MBR_crnti_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_crnti_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_crnti_specs_3 = {
	sizeof(struct L2MeasConfig__crnti),
	offsetof(struct L2MeasConfig__crnti, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crnti_3 = {
	"crnti",
	"crnti",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_crnti_tags_3,
	sizeof(asn_DEF_crnti_tags_3)
		/sizeof(asn_DEF_crnti_tags_3[0]) - 1, /* 1 */
	asn_DEF_crnti_tags_3,	/* Same as above */
	sizeof(asn_DEF_crnti_tags_3)
		/sizeof(asn_DEF_crnti_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_crnti_3,
	1,	/* Single element */
	&asn_SPC_crnti_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_L2MeasConfig_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct L2MeasConfig, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_POINTER, 1, offsetof(struct L2MeasConfig, crnti),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_crnti_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct L2MeasConfig, report_intervals),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_L2ReportInterval,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"report-intervals"
		},
};
static const int asn_MAP_L2MeasConfig_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_L2MeasConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_L2MeasConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* report-intervals */
};
asn_SEQUENCE_specifics_t asn_SPC_L2MeasConfig_specs_1 = {
	sizeof(struct L2MeasConfig),
	offsetof(struct L2MeasConfig, _asn_ctx),
	asn_MAP_L2MeasConfig_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_L2MeasConfig_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_L2MeasConfig = {
	"L2MeasConfig",
	"L2MeasConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_L2MeasConfig_tags_1,
	sizeof(asn_DEF_L2MeasConfig_tags_1)
		/sizeof(asn_DEF_L2MeasConfig_tags_1[0]), /* 1 */
	asn_DEF_L2MeasConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_L2MeasConfig_tags_1)
		/sizeof(asn_DEF_L2MeasConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_L2MeasConfig_1,
	3,	/* Elements count */
	&asn_SPC_L2MeasConfig_specs_1	/* Additional specs */
};

