/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_L2MeasReportInterval_H_
#define	_L2MeasReportInterval_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum L2MeasReportInterval {
	L2MeasReportInterval_no_report	= 0,
	L2MeasReportInterval_ms_10	= 1,
	L2MeasReportInterval_ms_50	= 2,
	L2MeasReportInterval_ms_100	= 3,
	L2MeasReportInterval_ms_200	= 4,
	L2MeasReportInterval_ms_500	= 5,
	L2MeasReportInterval_ms_1024	= 6,
	L2MeasReportInterval_s_10	= 7,
	L2MeasReportInterval_min_1	= 8,
	L2MeasReportInterval_min_2	= 9,
	L2MeasReportInterval_min_5	= 10
	/*
	 * Enumeration is extensible
	 */
} e_L2MeasReportInterval;

/* L2MeasReportInterval */
typedef long	 L2MeasReportInterval_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_L2MeasReportInterval_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_L2MeasReportInterval;
extern const asn_INTEGER_specifics_t asn_SPC_L2MeasReportInterval_specs_1;
asn_struct_free_f L2MeasReportInterval_free;
asn_struct_print_f L2MeasReportInterval_print;
asn_constr_check_f L2MeasReportInterval_constraint;
ber_type_decoder_f L2MeasReportInterval_decode_ber;
der_type_encoder_f L2MeasReportInterval_encode_der;
xer_type_decoder_f L2MeasReportInterval_decode_xer;
xer_type_encoder_f L2MeasReportInterval_encode_xer;
oer_type_decoder_f L2MeasReportInterval_decode_oer;
oer_type_encoder_f L2MeasReportInterval_encode_oer;
per_type_decoder_f L2MeasReportInterval_decode_uper;
per_type_encoder_f L2MeasReportInterval_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _L2MeasReportInterval_H_ */
#include <asn_internal.h>
