/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_L2ReportInterval_H_
#define	_L2ReportInterval_H_


#include <asn_application.h>

/* Including external dependencies */
#include "L2MeasReportInterval.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* L2ReportInterval */
typedef struct L2ReportInterval {
	L2MeasReportInterval_t	 t_radio_meas_report_per_ue;
	L2MeasReportInterval_t	 t_radio_meas_report_per_cell;
	L2MeasReportInterval_t	 t_radio_sched_report_per_ue;
	L2MeasReportInterval_t	 t_radio_sched_report_per_cell;
	L2MeasReportInterval_t	 t_pdcp_meas_report_per_ue;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} L2ReportInterval_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_L2ReportInterval;
extern asn_SEQUENCE_specifics_t asn_SPC_L2ReportInterval_specs_1;
extern asn_TYPE_member_t asn_MBR_L2ReportInterval_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _L2ReportInterval_H_ */
#include <asn_internal.h>
