/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_MeasID_H_
#define	_MeasID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasID__action_PR {
	MeasID__action_PR_NOTHING,	/* No components present */
	MeasID__action_PR_addmeasid,
	MeasID__action_PR_delmeasid,
	MeasID__action_PR_hototarget
} MeasID__action_PR;

/* MeasID */
typedef struct MeasID {
	long	 measobject_id;
	long	 reportconfig_id;
	struct MeasID__action {
		MeasID__action_PR present;
		union MeasID__action_u {
			struct MeasID__action__addmeasid {
				A_SEQUENCE_OF(long) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} addmeasid;
			struct MeasID__action__delmeasid {
				A_SEQUENCE_OF(long) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} delmeasid;
			BOOLEAN_t	 hototarget;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} action;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasID;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasID_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasID_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasID_H_ */
#include <asn_internal.h>
