/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_MeasObject_H_
#define	_MeasObject_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-Value.h"
#include "PhysCellId.h"
#include "Q-OffsetRange.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasObject */
typedef struct MeasObject {
	ARFCN_Value_t	 dl_freq;
	struct MeasObject__meas_cells {
		PhysCellId_t	 pci;
		Q_OffsetRange_t	*cellIndividualOffset	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *meas_cells;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasObject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasObject;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasObject_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasObject_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasObject_H_ */
#include <asn_internal.h>
