/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_PCI_ARFCN_H_
#define	_PCI_ARFCN_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysCellId.h"
#include "ARFCN-Value.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PCI-ARFCN */
typedef struct PCI_ARFCN {
	PhysCellId_t	 pci;
	ARFCN_Value_t	 earfcn_dl;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PCI_ARFCN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PCI_ARFCN;
extern asn_SEQUENCE_specifics_t asn_SPC_PCI_ARFCN_specs_1;
extern asn_TYPE_member_t asn_MBR_PCI_ARFCN_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PCI_ARFCN_H_ */
#include <asn_internal.h>
