/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_PDCPMeasReportPerUe_H_
#define	_PDCPMeasReportPerUe_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "CRNTI.h"
#include "QCI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PDCPMeasReportPerUe */
typedef struct PDCPMeasReportPerUe {
	ECGI_t	 ecgi;
	CRNTI_t	 crnti;
	struct PDCPMeasReportPerUe__qci_vals {
		A_SEQUENCE_OF(QCI_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} qci_vals;
	struct PDCPMeasReportPerUe__data_vol_dl {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} data_vol_dl;
	struct PDCPMeasReportPerUe__data_vol_ul {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} data_vol_ul;
	struct PDCPMeasReportPerUe__pkt_delay_dl {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pkt_delay_dl;
	struct PDCPMeasReportPerUe__pkt_delay_ul {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pkt_delay_ul;
	struct PDCPMeasReportPerUe__pkt_discard_rate_dl {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pkt_discard_rate_dl;
	struct PDCPMeasReportPerUe__pkt_loss_rate_dl {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pkt_loss_rate_dl;
	struct PDCPMeasReportPerUe__pkt_loss_rate_ul {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pkt_loss_rate_ul;
	struct PDCPMeasReportPerUe__throughput_dl {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} throughput_dl;
	struct PDCPMeasReportPerUe__throughput_ul {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} throughput_ul;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDCPMeasReportPerUe_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDCPMeasReportPerUe;
extern asn_SEQUENCE_specifics_t asn_SPC_PDCPMeasReportPerUe_specs_1;
extern asn_TYPE_member_t asn_MBR_PDCPMeasReportPerUe_1[12];

#ifdef __cplusplus
}
#endif

#endif	/* _PDCPMeasReportPerUe_H_ */
#include <asn_internal.h>
