/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_PerParam_H_
#define	_PerParam_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PerParam__report_interval_ms {
	PerParam__report_interval_ms_ms_120	= 0,
	PerParam__report_interval_ms_ms_240	= 1,
	PerParam__report_interval_ms_ms_480	= 2,
	PerParam__report_interval_ms_ms_640	= 3,
	PerParam__report_interval_ms_ms_1024	= 4,
	PerParam__report_interval_ms_ms_2048	= 5,
	PerParam__report_interval_ms_ms_5120	= 6,
	PerParam__report_interval_ms_ms_10240	= 7,
	PerParam__report_interval_ms_min_1	= 8,
	PerParam__report_interval_ms_min_6	= 9,
	PerParam__report_interval_ms_min_12	= 10,
	PerParam__report_interval_ms_min_30	= 11,
	PerParam__report_interval_ms_min_60	= 12
} e_PerParam__report_interval_ms;

/* PerParam */
typedef struct PerParam {
	long	 report_interval_ms;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerParam_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_report_interval_ms_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PerParam;
extern asn_SEQUENCE_specifics_t asn_SPC_PerParam_specs_1;
extern asn_TYPE_member_t asn_MBR_PerParam_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PerParam_H_ */
#include <asn_internal.h>
