/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "PerParam.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_report_interval_ms_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_report_interval_ms_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  12 }	/* (0..12) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_report_interval_ms_value2enum_2[] = {
	{ 0,	6,	"ms-120" },
	{ 1,	6,	"ms-240" },
	{ 2,	6,	"ms-480" },
	{ 3,	6,	"ms-640" },
	{ 4,	7,	"ms-1024" },
	{ 5,	7,	"ms-2048" },
	{ 6,	7,	"ms-5120" },
	{ 7,	8,	"ms-10240" },
	{ 8,	5,	"min-1" },
	{ 9,	5,	"min-6" },
	{ 10,	6,	"min-12" },
	{ 11,	6,	"min-30" },
	{ 12,	6,	"min-60" }
};
static const unsigned int asn_MAP_report_interval_ms_enum2value_2[] = {
	8,	/* min-1(8) */
	10,	/* min-12(10) */
	11,	/* min-30(11) */
	9,	/* min-6(9) */
	12,	/* min-60(12) */
	4,	/* ms-1024(4) */
	7,	/* ms-10240(7) */
	0,	/* ms-120(0) */
	5,	/* ms-2048(5) */
	1,	/* ms-240(1) */
	2,	/* ms-480(2) */
	6,	/* ms-5120(6) */
	3	/* ms-640(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_report_interval_ms_specs_2 = {
	asn_MAP_report_interval_ms_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_report_interval_ms_enum2value_2,	/* N => "tag"; sorted by N */
	13,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_report_interval_ms_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_report_interval_ms_2 = {
	"report-interval-ms",
	"report-interval-ms",
	&asn_OP_NativeEnumerated,
	asn_DEF_report_interval_ms_tags_2,
	sizeof(asn_DEF_report_interval_ms_tags_2)
		/sizeof(asn_DEF_report_interval_ms_tags_2[0]) - 1, /* 1 */
	asn_DEF_report_interval_ms_tags_2,	/* Same as above */
	sizeof(asn_DEF_report_interval_ms_tags_2)
		/sizeof(asn_DEF_report_interval_ms_tags_2[0]), /* 2 */
	{ &asn_OER_type_report_interval_ms_constr_2, &asn_PER_type_report_interval_ms_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_report_interval_ms_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PerParam_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PerParam, report_interval_ms),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_report_interval_ms_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"report-interval-ms"
		},
};
static const ber_tlv_tag_t asn_DEF_PerParam_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PerParam_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* report-interval-ms */
};
asn_SEQUENCE_specifics_t asn_SPC_PerParam_specs_1 = {
	sizeof(struct PerParam),
	offsetof(struct PerParam, _asn_ctx),
	asn_MAP_PerParam_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PerParam = {
	"PerParam",
	"PerParam",
	&asn_OP_SEQUENCE,
	asn_DEF_PerParam_tags_1,
	sizeof(asn_DEF_PerParam_tags_1)
		/sizeof(asn_DEF_PerParam_tags_1[0]), /* 1 */
	asn_DEF_PerParam_tags_1,	/* Same as above */
	sizeof(asn_DEF_PerParam_tags_1)
		/sizeof(asn_DEF_PerParam_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PerParam_1,
	1,	/* Elements count */
	&asn_SPC_PerParam_specs_1	/* Additional specs */
};

