/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "PRBUsage.h"

static int
memb_NativeInteger_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_NativeInteger_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_prb_usage_dl_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_prb_usage_ul_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_Member_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..100) */,
	-1};
static asn_per_constraints_t asn_PER_memb_Member_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_prb_usage_dl_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_prb_usage_dl_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_Member_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (0..100) */,
	-1};
static asn_per_constraints_t asn_PER_memb_Member_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_prb_usage_ul_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_prb_usage_ul_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_prb_usage_dl_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_prb_usage_dl_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_prb_usage_ul_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_prb_usage_ul_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_prb_usage_dl_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_Member_constr_3, &asn_PER_memb_Member_constr_3,  memb_NativeInteger_constraint_2 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_prb_usage_dl_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_prb_usage_dl_specs_2 = {
	sizeof(struct PRBUsage__prb_usage_dl),
	offsetof(struct PRBUsage__prb_usage_dl, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_prb_usage_dl_2 = {
	"prb-usage-dl",
	"prb-usage-dl",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_prb_usage_dl_tags_2,
	sizeof(asn_DEF_prb_usage_dl_tags_2)
		/sizeof(asn_DEF_prb_usage_dl_tags_2[0]) - 1, /* 1 */
	asn_DEF_prb_usage_dl_tags_2,	/* Same as above */
	sizeof(asn_DEF_prb_usage_dl_tags_2)
		/sizeof(asn_DEF_prb_usage_dl_tags_2[0]), /* 2 */
	{ &asn_OER_type_prb_usage_dl_constr_2, &asn_PER_type_prb_usage_dl_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_prb_usage_dl_2,
	1,	/* Single element */
	&asn_SPC_prb_usage_dl_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_prb_usage_ul_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_Member_constr_5, &asn_PER_memb_Member_constr_5,  memb_NativeInteger_constraint_4 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_prb_usage_ul_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_prb_usage_ul_specs_4 = {
	sizeof(struct PRBUsage__prb_usage_ul),
	offsetof(struct PRBUsage__prb_usage_ul, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_prb_usage_ul_4 = {
	"prb-usage-ul",
	"prb-usage-ul",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_prb_usage_ul_tags_4,
	sizeof(asn_DEF_prb_usage_ul_tags_4)
		/sizeof(asn_DEF_prb_usage_ul_tags_4[0]) - 1, /* 1 */
	asn_DEF_prb_usage_ul_tags_4,	/* Same as above */
	sizeof(asn_DEF_prb_usage_ul_tags_4)
		/sizeof(asn_DEF_prb_usage_ul_tags_4[0]), /* 2 */
	{ &asn_OER_type_prb_usage_ul_constr_4, &asn_PER_type_prb_usage_ul_constr_4, SEQUENCE_OF_constraint },
	asn_MBR_prb_usage_ul_4,
	1,	/* Single element */
	&asn_SPC_prb_usage_ul_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PRBUsage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PRBUsage, prb_usage_dl),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_prb_usage_dl_2,
		0,
		{ &asn_OER_memb_prb_usage_dl_constr_2, &asn_PER_memb_prb_usage_dl_constr_2,  memb_prb_usage_dl_constraint_1 },
		0, 0, /* No default value */
		"prb-usage-dl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PRBUsage, prb_usage_ul),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_prb_usage_ul_4,
		0,
		{ &asn_OER_memb_prb_usage_ul_constr_4, &asn_PER_memb_prb_usage_ul_constr_4,  memb_prb_usage_ul_constraint_1 },
		0, 0, /* No default value */
		"prb-usage-ul"
		},
};
static const ber_tlv_tag_t asn_DEF_PRBUsage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PRBUsage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* prb-usage-dl */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* prb-usage-ul */
};
asn_SEQUENCE_specifics_t asn_SPC_PRBUsage_specs_1 = {
	sizeof(struct PRBUsage),
	offsetof(struct PRBUsage, _asn_ctx),
	asn_MAP_PRBUsage_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PRBUsage = {
	"PRBUsage",
	"PRBUsage",
	&asn_OP_SEQUENCE,
	asn_DEF_PRBUsage_tags_1,
	sizeof(asn_DEF_PRBUsage_tags_1)
		/sizeof(asn_DEF_PRBUsage_tags_1[0]), /* 1 */
	asn_DEF_PRBUsage_tags_1,	/* Same as above */
	sizeof(asn_DEF_PRBUsage_tags_1)
		/sizeof(asn_DEF_PRBUsage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PRBUsage_1,
	2,	/* Elements count */
	&asn_SPC_PRBUsage_specs_1	/* Additional specs */
};

