/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "PropScell.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ca_direction_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_ca_direction_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ca_direction_value2enum_4[] = {
	{ 0,	2,	"dl" },
	{ 1,	2,	"ul" },
	{ 2,	4,	"both" }
};
static const unsigned int asn_MAP_ca_direction_enum2value_4[] = {
	2,	/* both(2) */
	0,	/* dl(0) */
	1	/* ul(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_ca_direction_specs_4 = {
	asn_MAP_ca_direction_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_ca_direction_enum2value_4,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ca_direction_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ca_direction_4 = {
	"ca-direction",
	"ca-direction",
	&asn_OP_NativeEnumerated,
	asn_DEF_ca_direction_tags_4,
	sizeof(asn_DEF_ca_direction_tags_4)
		/sizeof(asn_DEF_ca_direction_tags_4[0]) - 1, /* 1 */
	asn_DEF_ca_direction_tags_4,	/* Same as above */
	sizeof(asn_DEF_ca_direction_tags_4)
		/sizeof(asn_DEF_ca_direction_tags_4[0]), /* 2 */
	{ &asn_OER_type_ca_direction_constr_4, &asn_PER_type_ca_direction_constr_4, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ca_direction_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PropScell_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PropScell, pci_arfcn),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PCI_ARFCN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pci-arfcn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PropScell, cross_carrier_sched_enable),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cross-carrier-sched-enable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PropScell, ca_direction),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ca_direction_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ca-direction"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PropScell, deact_timer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deact-timer"
		},
};
static const ber_tlv_tag_t asn_DEF_PropScell_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PropScell_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pci-arfcn */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cross-carrier-sched-enable */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ca-direction */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* deact-timer */
};
asn_SEQUENCE_specifics_t asn_SPC_PropScell_specs_1 = {
	sizeof(struct PropScell),
	offsetof(struct PropScell, _asn_ctx),
	asn_MAP_PropScell_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PropScell = {
	"PropScell",
	"PropScell",
	&asn_OP_SEQUENCE,
	asn_DEF_PropScell_tags_1,
	sizeof(asn_DEF_PropScell_tags_1)
		/sizeof(asn_DEF_PropScell_tags_1[0]), /* 1 */
	asn_DEF_PropScell_tags_1,	/* Same as above */
	sizeof(asn_DEF_PropScell_tags_1)
		/sizeof(asn_DEF_PropScell_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PropScell_1,
	4,	/* Elements count */
	&asn_SPC_PropScell_specs_1	/* Additional specs */
};

