/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_PropScell_H_
#define	_PropScell_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PCI-ARFCN.h"
#include <BOOLEAN.h>
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PropScell__ca_direction {
	PropScell__ca_direction_dl	= 0,
	PropScell__ca_direction_ul	= 1,
	PropScell__ca_direction_both	= 2
} e_PropScell__ca_direction;

/* PropScell */
typedef struct PropScell {
	PCI_ARFCN_t	 pci_arfcn;
	BOOLEAN_t	 cross_carrier_sched_enable;
	long	 ca_direction;
	long	 deact_timer;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PropScell_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ca_direction_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PropScell;
extern asn_SEQUENCE_specifics_t asn_SPC_PropScell_specs_1;
extern asn_TYPE_member_t asn_MBR_PropScell_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _PropScell_H_ */
#include <asn_internal.h>
