/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_RadioMeasReportPerCell_H_
#define	_RadioMeasReportPerCell_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RadioMeasReportPerCell */
typedef struct RadioMeasReportPerCell {
	ECGI_t	 ecgi;
	struct RadioMeasReportPerCell__pusch_intf_power_hist {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pusch_intf_power_hist;
	struct RadioMeasReportPerCell__pucch_intf_power_hist {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pucch_intf_power_hist;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioMeasReportPerCell_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioMeasReportPerCell;
extern asn_SEQUENCE_specifics_t asn_SPC_RadioMeasReportPerCell_specs_1;
extern asn_TYPE_member_t asn_MBR_RadioMeasReportPerCell_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RadioMeasReportPerCell_H_ */
#include <asn_internal.h>
