/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_RadioRepPerServCell_H_
#define	_RadioRepPerServCell_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RadioRepPerServCell */
typedef struct RadioRepPerServCell {
	ECGI_t	 ecgi;
	struct RadioRepPerServCell__cqi_hist {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} cqi_hist;
	struct RadioRepPerServCell__ri_hist {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ri_hist;
	struct RadioRepPerServCell__pusch_sinr_hist {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pusch_sinr_hist;
	struct RadioRepPerServCell__pucch_sinr_hist {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pucch_sinr_hist;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioRepPerServCell_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioRepPerServCell;
extern asn_SEQUENCE_specifics_t asn_SPC_RadioRepPerServCell_specs_1;
extern asn_TYPE_member_t asn_MBR_RadioRepPerServCell_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RadioRepPerServCell_H_ */
#include <asn_internal.h>
