/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "RadioMeasReportPerCell.h"

static int
memb_pusch_intf_power_hist_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size == 17)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pucch_intf_power_hist_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size == 17)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_pusch_intf_power_hist_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	17	/* (SIZE(17..17)) */};
static asn_per_constraints_t asn_PER_type_pusch_intf_power_hist_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  17,  17 }	/* (SIZE(17..17)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_pucch_intf_power_hist_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	17	/* (SIZE(17..17)) */};
static asn_per_constraints_t asn_PER_type_pucch_intf_power_hist_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  17,  17 }	/* (SIZE(17..17)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_pusch_intf_power_hist_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	17	/* (SIZE(17..17)) */};
static asn_per_constraints_t asn_PER_memb_pusch_intf_power_hist_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  17,  17 }	/* (SIZE(17..17)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_pucch_intf_power_hist_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	17	/* (SIZE(17..17)) */};
static asn_per_constraints_t asn_PER_memb_pucch_intf_power_hist_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  17,  17 }	/* (SIZE(17..17)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_pusch_intf_power_hist_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_pusch_intf_power_hist_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_pusch_intf_power_hist_specs_3 = {
	sizeof(struct RadioMeasReportPerCell__pusch_intf_power_hist),
	offsetof(struct RadioMeasReportPerCell__pusch_intf_power_hist, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pusch_intf_power_hist_3 = {
	"pusch-intf-power-hist",
	"pusch-intf-power-hist",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_pusch_intf_power_hist_tags_3,
	sizeof(asn_DEF_pusch_intf_power_hist_tags_3)
		/sizeof(asn_DEF_pusch_intf_power_hist_tags_3[0]) - 1, /* 1 */
	asn_DEF_pusch_intf_power_hist_tags_3,	/* Same as above */
	sizeof(asn_DEF_pusch_intf_power_hist_tags_3)
		/sizeof(asn_DEF_pusch_intf_power_hist_tags_3[0]), /* 2 */
	{ &asn_OER_type_pusch_intf_power_hist_constr_3, &asn_PER_type_pusch_intf_power_hist_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_pusch_intf_power_hist_3,
	1,	/* Single element */
	&asn_SPC_pusch_intf_power_hist_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_pucch_intf_power_hist_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_pucch_intf_power_hist_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_pucch_intf_power_hist_specs_5 = {
	sizeof(struct RadioMeasReportPerCell__pucch_intf_power_hist),
	offsetof(struct RadioMeasReportPerCell__pucch_intf_power_hist, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pucch_intf_power_hist_5 = {
	"pucch-intf-power-hist",
	"pucch-intf-power-hist",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_pucch_intf_power_hist_tags_5,
	sizeof(asn_DEF_pucch_intf_power_hist_tags_5)
		/sizeof(asn_DEF_pucch_intf_power_hist_tags_5[0]) - 1, /* 1 */
	asn_DEF_pucch_intf_power_hist_tags_5,	/* Same as above */
	sizeof(asn_DEF_pucch_intf_power_hist_tags_5)
		/sizeof(asn_DEF_pucch_intf_power_hist_tags_5[0]), /* 2 */
	{ &asn_OER_type_pucch_intf_power_hist_constr_5, &asn_PER_type_pucch_intf_power_hist_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_pucch_intf_power_hist_5,
	1,	/* Single element */
	&asn_SPC_pucch_intf_power_hist_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RadioMeasReportPerCell_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RadioMeasReportPerCell, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioMeasReportPerCell, pusch_intf_power_hist),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_pusch_intf_power_hist_3,
		0,
		{ &asn_OER_memb_pusch_intf_power_hist_constr_3, &asn_PER_memb_pusch_intf_power_hist_constr_3,  memb_pusch_intf_power_hist_constraint_1 },
		0, 0, /* No default value */
		"pusch-intf-power-hist"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioMeasReportPerCell, pucch_intf_power_hist),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_pucch_intf_power_hist_5,
		0,
		{ &asn_OER_memb_pucch_intf_power_hist_constr_5, &asn_PER_memb_pucch_intf_power_hist_constr_5,  memb_pucch_intf_power_hist_constraint_1 },
		0, 0, /* No default value */
		"pucch-intf-power-hist"
		},
};
static const ber_tlv_tag_t asn_DEF_RadioMeasReportPerCell_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RadioMeasReportPerCell_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pusch-intf-power-hist */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* pucch-intf-power-hist */
};
asn_SEQUENCE_specifics_t asn_SPC_RadioMeasReportPerCell_specs_1 = {
	sizeof(struct RadioMeasReportPerCell),
	offsetof(struct RadioMeasReportPerCell, _asn_ctx),
	asn_MAP_RadioMeasReportPerCell_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RadioMeasReportPerCell = {
	"RadioMeasReportPerCell",
	"RadioMeasReportPerCell",
	&asn_OP_SEQUENCE,
	asn_DEF_RadioMeasReportPerCell_tags_1,
	sizeof(asn_DEF_RadioMeasReportPerCell_tags_1)
		/sizeof(asn_DEF_RadioMeasReportPerCell_tags_1[0]), /* 1 */
	asn_DEF_RadioMeasReportPerCell_tags_1,	/* Same as above */
	sizeof(asn_DEF_RadioMeasReportPerCell_tags_1)
		/sizeof(asn_DEF_RadioMeasReportPerCell_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RadioMeasReportPerCell_1,
	3,	/* Elements count */
	&asn_SPC_RadioMeasReportPerCell_specs_1	/* Additional specs */
};

