/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_RadioMeasReportPerUE_H_
#define	_RadioMeasReportPerUE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "CRNTI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RadioRepPerServCell;

/* RadioMeasReportPerUE */
typedef struct RadioMeasReportPerUE {
	ECGI_t	 ecgi;
	CRNTI_t	 crnti;
	struct RadioMeasReportPerUE__radio_report_serv_cells {
		A_SEQUENCE_OF(struct RadioRepPerServCell) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} radio_report_serv_cells;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioMeasReportPerUE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioMeasReportPerUE;
extern asn_SEQUENCE_specifics_t asn_SPC_RadioMeasReportPerUE_specs_1;
extern asn_TYPE_member_t asn_MBR_RadioMeasReportPerUE_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RadioRepPerServCell.h"

#endif	/* _RadioMeasReportPerUE_H_ */
#include <asn_internal.h>
