/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "RadioRepPerServCell.h"

static int
memb_cqi_hist_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size == 16)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ri_hist_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size == 2)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pusch_sinr_hist_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size == 14)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pucch_sinr_hist_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size == 14)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_cqi_hist_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	16	/* (SIZE(16..16)) */};
static asn_per_constraints_t asn_PER_type_cqi_hist_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  16,  16 }	/* (SIZE(16..16)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ri_hist_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_type_ri_hist_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_pusch_sinr_hist_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	14	/* (SIZE(14..14)) */};
static asn_per_constraints_t asn_PER_type_pusch_sinr_hist_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  14,  14 }	/* (SIZE(14..14)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_pucch_sinr_hist_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	14	/* (SIZE(14..14)) */};
static asn_per_constraints_t asn_PER_type_pucch_sinr_hist_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  14,  14 }	/* (SIZE(14..14)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_cqi_hist_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	16	/* (SIZE(16..16)) */};
static asn_per_constraints_t asn_PER_memb_cqi_hist_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  16,  16 }	/* (SIZE(16..16)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ri_hist_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_ri_hist_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_pusch_sinr_hist_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	14	/* (SIZE(14..14)) */};
static asn_per_constraints_t asn_PER_memb_pusch_sinr_hist_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  14,  14 }	/* (SIZE(14..14)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_pucch_sinr_hist_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	14	/* (SIZE(14..14)) */};
static asn_per_constraints_t asn_PER_memb_pucch_sinr_hist_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  14,  14 }	/* (SIZE(14..14)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_cqi_hist_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_cqi_hist_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_cqi_hist_specs_3 = {
	sizeof(struct RadioRepPerServCell__cqi_hist),
	offsetof(struct RadioRepPerServCell__cqi_hist, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cqi_hist_3 = {
	"cqi-hist",
	"cqi-hist",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_cqi_hist_tags_3,
	sizeof(asn_DEF_cqi_hist_tags_3)
		/sizeof(asn_DEF_cqi_hist_tags_3[0]) - 1, /* 1 */
	asn_DEF_cqi_hist_tags_3,	/* Same as above */
	sizeof(asn_DEF_cqi_hist_tags_3)
		/sizeof(asn_DEF_cqi_hist_tags_3[0]), /* 2 */
	{ &asn_OER_type_cqi_hist_constr_3, &asn_PER_type_cqi_hist_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_cqi_hist_3,
	1,	/* Single element */
	&asn_SPC_cqi_hist_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ri_hist_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ri_hist_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ri_hist_specs_5 = {
	sizeof(struct RadioRepPerServCell__ri_hist),
	offsetof(struct RadioRepPerServCell__ri_hist, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ri_hist_5 = {
	"ri-hist",
	"ri-hist",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ri_hist_tags_5,
	sizeof(asn_DEF_ri_hist_tags_5)
		/sizeof(asn_DEF_ri_hist_tags_5[0]) - 1, /* 1 */
	asn_DEF_ri_hist_tags_5,	/* Same as above */
	sizeof(asn_DEF_ri_hist_tags_5)
		/sizeof(asn_DEF_ri_hist_tags_5[0]), /* 2 */
	{ &asn_OER_type_ri_hist_constr_5, &asn_PER_type_ri_hist_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_ri_hist_5,
	1,	/* Single element */
	&asn_SPC_ri_hist_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_pusch_sinr_hist_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_pusch_sinr_hist_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_pusch_sinr_hist_specs_7 = {
	sizeof(struct RadioRepPerServCell__pusch_sinr_hist),
	offsetof(struct RadioRepPerServCell__pusch_sinr_hist, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pusch_sinr_hist_7 = {
	"pusch-sinr-hist",
	"pusch-sinr-hist",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_pusch_sinr_hist_tags_7,
	sizeof(asn_DEF_pusch_sinr_hist_tags_7)
		/sizeof(asn_DEF_pusch_sinr_hist_tags_7[0]) - 1, /* 1 */
	asn_DEF_pusch_sinr_hist_tags_7,	/* Same as above */
	sizeof(asn_DEF_pusch_sinr_hist_tags_7)
		/sizeof(asn_DEF_pusch_sinr_hist_tags_7[0]), /* 2 */
	{ &asn_OER_type_pusch_sinr_hist_constr_7, &asn_PER_type_pusch_sinr_hist_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_pusch_sinr_hist_7,
	1,	/* Single element */
	&asn_SPC_pusch_sinr_hist_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_pucch_sinr_hist_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_pucch_sinr_hist_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_pucch_sinr_hist_specs_9 = {
	sizeof(struct RadioRepPerServCell__pucch_sinr_hist),
	offsetof(struct RadioRepPerServCell__pucch_sinr_hist, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pucch_sinr_hist_9 = {
	"pucch-sinr-hist",
	"pucch-sinr-hist",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_pucch_sinr_hist_tags_9,
	sizeof(asn_DEF_pucch_sinr_hist_tags_9)
		/sizeof(asn_DEF_pucch_sinr_hist_tags_9[0]) - 1, /* 1 */
	asn_DEF_pucch_sinr_hist_tags_9,	/* Same as above */
	sizeof(asn_DEF_pucch_sinr_hist_tags_9)
		/sizeof(asn_DEF_pucch_sinr_hist_tags_9[0]), /* 2 */
	{ &asn_OER_type_pucch_sinr_hist_constr_9, &asn_PER_type_pucch_sinr_hist_constr_9, SEQUENCE_OF_constraint },
	asn_MBR_pucch_sinr_hist_9,
	1,	/* Single element */
	&asn_SPC_pucch_sinr_hist_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RadioRepPerServCell_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RadioRepPerServCell, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioRepPerServCell, cqi_hist),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_cqi_hist_3,
		0,
		{ &asn_OER_memb_cqi_hist_constr_3, &asn_PER_memb_cqi_hist_constr_3,  memb_cqi_hist_constraint_1 },
		0, 0, /* No default value */
		"cqi-hist"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioRepPerServCell, ri_hist),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ri_hist_5,
		0,
		{ &asn_OER_memb_ri_hist_constr_5, &asn_PER_memb_ri_hist_constr_5,  memb_ri_hist_constraint_1 },
		0, 0, /* No default value */
		"ri-hist"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioRepPerServCell, pusch_sinr_hist),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_pusch_sinr_hist_7,
		0,
		{ &asn_OER_memb_pusch_sinr_hist_constr_7, &asn_PER_memb_pusch_sinr_hist_constr_7,  memb_pusch_sinr_hist_constraint_1 },
		0, 0, /* No default value */
		"pusch-sinr-hist"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioRepPerServCell, pucch_sinr_hist),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_pucch_sinr_hist_9,
		0,
		{ &asn_OER_memb_pucch_sinr_hist_constr_9, &asn_PER_memb_pucch_sinr_hist_constr_9,  memb_pucch_sinr_hist_constraint_1 },
		0, 0, /* No default value */
		"pucch-sinr-hist"
		},
};
static const ber_tlv_tag_t asn_DEF_RadioRepPerServCell_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RadioRepPerServCell_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cqi-hist */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ri-hist */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* pusch-sinr-hist */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* pucch-sinr-hist */
};
asn_SEQUENCE_specifics_t asn_SPC_RadioRepPerServCell_specs_1 = {
	sizeof(struct RadioRepPerServCell),
	offsetof(struct RadioRepPerServCell, _asn_ctx),
	asn_MAP_RadioRepPerServCell_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RadioRepPerServCell = {
	"RadioRepPerServCell",
	"RadioRepPerServCell",
	&asn_OP_SEQUENCE,
	asn_DEF_RadioRepPerServCell_tags_1,
	sizeof(asn_DEF_RadioRepPerServCell_tags_1)
		/sizeof(asn_DEF_RadioRepPerServCell_tags_1[0]), /* 1 */
	asn_DEF_RadioRepPerServCell_tags_1,	/* Same as above */
	sizeof(asn_DEF_RadioRepPerServCell_tags_1)
		/sizeof(asn_DEF_RadioRepPerServCell_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RadioRepPerServCell_1,
	5,	/* Elements count */
	&asn_SPC_RadioRepPerServCell_specs_1	/* Additional specs */
};

