/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ReconfIndReason_H_
#define	_ReconfIndReason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReconfIndReason {
	ReconfIndReason_rlf	= 0,
	ReconfIndReason_ho_fail	= 1,
	ReconfIndReason_others	= 2
	/*
	 * Enumeration is extensible
	 */
} e_ReconfIndReason;

/* ReconfIndReason */
typedef long	 ReconfIndReason_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ReconfIndReason_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ReconfIndReason;
extern const asn_INTEGER_specifics_t asn_SPC_ReconfIndReason_specs_1;
asn_struct_free_f ReconfIndReason_free;
asn_struct_print_f ReconfIndReason_print;
asn_constr_check_f ReconfIndReason_constraint;
ber_type_decoder_f ReconfIndReason_decode_ber;
der_type_encoder_f ReconfIndReason_encode_der;
xer_type_decoder_f ReconfIndReason_decode_xer;
xer_type_encoder_f ReconfIndReason_encode_xer;
oer_type_decoder_f ReconfIndReason_decode_oer;
oer_type_encoder_f ReconfIndReason_encode_oer;
per_type_decoder_f ReconfIndReason_decode_uper;
per_type_encoder_f ReconfIndReason_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReconfIndReason_H_ */
#include <asn_internal.h>
