/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_RelCause_H_
#define	_RelCause_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RelCause {
	RelCause_inactivity	= 0,
	RelCause_rlf	= 1,
	RelCause_others	= 2
	/*
	 * Enumeration is extensible
	 */
} e_RelCause;

/* RelCause */
typedef long	 RelCause_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RelCause_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RelCause;
extern const asn_INTEGER_specifics_t asn_SPC_RelCause_specs_1;
asn_struct_free_f RelCause_free;
asn_struct_print_f RelCause_print;
asn_constr_check_f RelCause_constraint;
ber_type_decoder_f RelCause_decode_ber;
der_type_encoder_f RelCause_encode_der;
xer_type_decoder_f RelCause_decode_xer;
xer_type_encoder_f RelCause_encode_xer;
oer_type_decoder_f RelCause_decode_oer;
oer_type_encoder_f RelCause_encode_oer;
per_type_decoder_f RelCause_decode_uper;
per_type_encoder_f RelCause_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RelCause_H_ */
#include <asn_internal.h>
