/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ReportConfig_H_
#define	_ReportConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "Hysteresis.h"
#include "TimeToTrigger.h"
#include "PerParam.h"
#include "A1Param.h"
#include "A2Param.h"
#include "A3Param.h"
#include "A4Param.h"
#include "A5Param.h"
#include "A6Param.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportConfig__report_params__params_PR {
	ReportConfig__report_params__params_PR_NOTHING,	/* No components present */
	ReportConfig__report_params__params_PR_per_param,
	ReportConfig__report_params__params_PR_a1param,
	ReportConfig__report_params__params_PR_a2param,
	ReportConfig__report_params__params_PR_a3param,
	ReportConfig__report_params__params_PR_a4param,
	ReportConfig__report_params__params_PR_a5param,
	ReportConfig__report_params__params_PR_a6param
} ReportConfig__report_params__params_PR;
typedef enum ReportConfig__triggerQuantity {
	ReportConfig__triggerQuantity_rsrp	= 0,
	ReportConfig__triggerQuantity_rsrq	= 1
} e_ReportConfig__triggerQuantity;
typedef enum ReportConfig__reportQuantity {
	ReportConfig__reportQuantity_sameAsTriggerQuantity	= 0,
	ReportConfig__reportQuantity_both	= 1
} e_ReportConfig__reportQuantity;

/* ReportConfig */
typedef struct ReportConfig {
	struct ReportConfig__report_params {
		struct ReportConfig__report_params__params {
			ReportConfig__report_params__params_PR present;
			union ReportConfig__report_params__params_u {
				PerParam_t	 per_param;
				A1Param_t	 a1param;
				A2Param_t	 a2param;
				A3Param_t	 a3param;
				A4Param_t	 a4param;
				A5Param_t	 a5param;
				A6Param_t	 a6param;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} params;
		Hysteresis_t	 hysteresis;
		TimeToTrigger_t	 timetotrigger;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} report_params;
	long	 triggerQuantity;
	long	 reportQuantity;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_triggerQuantity_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_reportQuantity_16;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ReportConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_ReportConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportConfig_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ReportConfig_H_ */
#include <asn_internal.h>
