/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "RRCMeasConfig.h"

static asn_TYPE_member_t asn_MBR_crnti_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_crnti_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_crnti_specs_3 = {
	sizeof(struct RRCMeasConfig__crnti),
	offsetof(struct RRCMeasConfig__crnti, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crnti_3 = {
	"crnti",
	"crnti",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_crnti_tags_3,
	sizeof(asn_DEF_crnti_tags_3)
		/sizeof(asn_DEF_crnti_tags_3[0]) - 1, /* 1 */
	asn_DEF_crnti_tags_3,	/* Same as above */
	sizeof(asn_DEF_crnti_tags_3)
		/sizeof(asn_DEF_crnti_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_crnti_3,
	1,	/* Single element */
	&asn_SPC_crnti_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_meas_objects_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MeasObject,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_meas_objects_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_meas_objects_specs_5 = {
	sizeof(struct RRCMeasConfig__meas_objects),
	offsetof(struct RRCMeasConfig__meas_objects, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_meas_objects_5 = {
	"meas-objects",
	"meas-objects",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_meas_objects_tags_5,
	sizeof(asn_DEF_meas_objects_tags_5)
		/sizeof(asn_DEF_meas_objects_tags_5[0]) - 1, /* 1 */
	asn_DEF_meas_objects_tags_5,	/* Same as above */
	sizeof(asn_DEF_meas_objects_tags_5)
		/sizeof(asn_DEF_meas_objects_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_meas_objects_5,
	1,	/* Single element */
	&asn_SPC_meas_objects_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_report_configs_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ReportConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_report_configs_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_report_configs_specs_7 = {
	sizeof(struct RRCMeasConfig__report_configs),
	offsetof(struct RRCMeasConfig__report_configs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_report_configs_7 = {
	"report-configs",
	"report-configs",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_report_configs_tags_7,
	sizeof(asn_DEF_report_configs_tags_7)
		/sizeof(asn_DEF_report_configs_tags_7[0]) - 1, /* 1 */
	asn_DEF_report_configs_tags_7,	/* Same as above */
	sizeof(asn_DEF_report_configs_tags_7)
		/sizeof(asn_DEF_report_configs_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_report_configs_7,
	1,	/* Single element */
	&asn_SPC_report_configs_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_meas_ids_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MeasID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_meas_ids_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_meas_ids_specs_9 = {
	sizeof(struct RRCMeasConfig__meas_ids),
	offsetof(struct RRCMeasConfig__meas_ids, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_meas_ids_9 = {
	"meas-ids",
	"meas-ids",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_meas_ids_tags_9,
	sizeof(asn_DEF_meas_ids_tags_9)
		/sizeof(asn_DEF_meas_ids_tags_9[0]) - 1, /* 1 */
	asn_DEF_meas_ids_tags_9,	/* Same as above */
	sizeof(asn_DEF_meas_ids_tags_9)
		/sizeof(asn_DEF_meas_ids_tags_9[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_meas_ids_9,
	1,	/* Single element */
	&asn_SPC_meas_ids_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RRCMeasConfig_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCMeasConfig, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCMeasConfig, crnti),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_crnti_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCMeasConfig, meas_objects),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_meas_objects_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"meas-objects"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCMeasConfig, report_configs),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_report_configs_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"report-configs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCMeasConfig, meas_ids),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_meas_ids_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"meas-ids"
		},
};
static const int asn_MAP_RRCMeasConfig_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_RRCMeasConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RRCMeasConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* meas-objects */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* report-configs */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* meas-ids */
};
asn_SEQUENCE_specifics_t asn_SPC_RRCMeasConfig_specs_1 = {
	sizeof(struct RRCMeasConfig),
	offsetof(struct RRCMeasConfig, _asn_ctx),
	asn_MAP_RRCMeasConfig_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RRCMeasConfig_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RRCMeasConfig = {
	"RRCMeasConfig",
	"RRCMeasConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_RRCMeasConfig_tags_1,
	sizeof(asn_DEF_RRCMeasConfig_tags_1)
		/sizeof(asn_DEF_RRCMeasConfig_tags_1[0]), /* 1 */
	asn_DEF_RRCMeasConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCMeasConfig_tags_1)
		/sizeof(asn_DEF_RRCMeasConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RRCMeasConfig_1,
	5,	/* Elements count */
	&asn_SPC_RRCMeasConfig_specs_1	/* Additional specs */
};

