/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_RRCMeasConfig_H_
#define	_RRCMeasConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "CRNTI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasObject;
struct ReportConfig;
struct MeasID;

/* RRCMeasConfig */
typedef struct RRCMeasConfig {
	ECGI_t	 ecgi;
	struct RRCMeasConfig__crnti {
		A_SEQUENCE_OF(CRNTI_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *crnti;
	struct RRCMeasConfig__meas_objects {
		A_SEQUENCE_OF(struct MeasObject) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} meas_objects;
	struct RRCMeasConfig__report_configs {
		A_SEQUENCE_OF(struct ReportConfig) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} report_configs;
	struct RRCMeasConfig__meas_ids {
		A_SEQUENCE_OF(struct MeasID) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} meas_ids;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCMeasConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCMeasConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCMeasConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCMeasConfig_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasObject.h"
#include "ReportConfig.h"
#include "MeasID.h"

#endif	/* _RRCMeasConfig_H_ */
#include <asn_internal.h>
