/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_RRMConfig_H_
#define	_RRMConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "CRNTI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "XICIC-PA.h"
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PCI_ARFCN;

/* RRMConfig */
typedef struct RRMConfig {
	ECGI_t	 ecgi;
	struct RRMConfig__crnti {
		A_SEQUENCE_OF(CRNTI_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *crnti;
	struct PCI_ARFCN	*pci_arfcn	/* OPTIONAL */;
	struct RRMConfig__pa {
		A_SEQUENCE_OF(XICIC_PA_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pa;
	struct RRMConfig__start_prb_dl {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *start_prb_dl;
	struct RRMConfig__end_prb_dl {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *end_prb_dl;
	struct RRMConfig__subframe_bitmask_dl {
		A_SEQUENCE_OF(BIT_STRING_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *subframe_bitmask_dl;
	struct RRMConfig__p0_ue_pusch {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *p0_ue_pusch;
	struct RRMConfig__start_prb_ul {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *start_prb_ul;
	struct RRMConfig__end_prb_ul {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *end_prb_ul;
	struct RRMConfig__subframe_bitmask_ul {
		A_SEQUENCE_OF(BIT_STRING_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *subframe_bitmask_ul;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRMConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRMConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_RRMConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_RRMConfig_1[11];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PCI-ARFCN.h"

#endif	/* _RRMConfig_H_ */
#include <asn_internal.h>
