/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_RRMConfigStatus_H_
#define	_RRMConfigStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "CRNTI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRMConfigStatus__status__Member {
	RRMConfigStatus__status__Member_success	= 0,
	RRMConfigStatus__status__Member_failure	= 1
} e_RRMConfigStatus__status__Member;

/* RRMConfigStatus */
typedef struct RRMConfigStatus {
	ECGI_t	 ecgi;
	struct RRMConfigStatus__crnti {
		A_SEQUENCE_OF(CRNTI_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *crnti;
	struct RRMConfigStatus__status {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} status;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRMConfigStatus_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_Member_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRMConfigStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_RRMConfigStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_RRMConfigStatus_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RRMConfigStatus_H_ */
#include <asn_internal.h>
