/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_RXSigMeasReport_H_
#define	_RXSigMeasReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "CRNTI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RXSigReport;

/* Forward definitions */
typedef struct RXSigMeasReport__cell_meas_reports__Member {
	A_SEQUENCE_OF(struct RXSigReport) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RXSigMeasReport__cell_meas_reports__Member;

/* RXSigMeasReport */
typedef struct RXSigMeasReport {
	struct RXSigMeasReport__crnti {
		A_SEQUENCE_OF(CRNTI_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} crnti;
	ECGI_t	 ecgi;
	struct RXSigMeasReport__cell_meas_reports {
		A_SEQUENCE_OF(RXSigMeasReport__cell_meas_reports__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} cell_meas_reports;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RXSigMeasReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RXSigMeasReport;
extern asn_SEQUENCE_specifics_t asn_SPC_RXSigMeasReport_specs_1;
extern asn_TYPE_member_t asn_MBR_RXSigMeasReport_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RXSigReport.h"

#endif	/* _RXSigMeasReport_H_ */
#include <asn_internal.h>
