/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_RXSigReport_H_
#define	_RXSigReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PCI-ARFCN.h"
#include "RSRP-Range.h"
#include "RSRQ-Range.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ECGI;

/* RXSigReport */
typedef struct RXSigReport {
	PCI_ARFCN_t	 pci_arfcn;
	struct ECGI	*ecgi	/* OPTIONAL */;
	RSRP_Range_t	*rsrp	/* OPTIONAL */;
	RSRQ_Range_t	*rsrq	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RXSigReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RXSigReport;
extern asn_SEQUENCE_specifics_t asn_SPC_RXSigReport_specs_1;
extern asn_TYPE_member_t asn_MBR_RXSigReport_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ECGI.h"

#endif	/* _RXSigReport_H_ */
#include <asn_internal.h>
