/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "RXSigMeasReport.h"

static asn_TYPE_member_t asn_MBR_crnti_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_crnti_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_crnti_specs_2 = {
	sizeof(struct RXSigMeasReport__crnti),
	offsetof(struct RXSigMeasReport__crnti, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crnti_2 = {
	"crnti",
	"crnti",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_crnti_tags_2,
	sizeof(asn_DEF_crnti_tags_2)
		/sizeof(asn_DEF_crnti_tags_2[0]) - 1, /* 1 */
	asn_DEF_crnti_tags_2,	/* Same as above */
	sizeof(asn_DEF_crnti_tags_2)
		/sizeof(asn_DEF_crnti_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_crnti_2,
	1,	/* Single element */
	&asn_SPC_crnti_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RXSigReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_Member_specs_6 = {
	sizeof(struct RXSigMeasReport__cell_meas_reports__Member),
	offsetof(struct RXSigMeasReport__cell_meas_reports__Member, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_6 = {
	"SEQUENCE OF",
	"SEQUENCE_OF",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_Member_tags_6,
	sizeof(asn_DEF_Member_tags_6)
		/sizeof(asn_DEF_Member_tags_6[0]), /* 1 */
	asn_DEF_Member_tags_6,	/* Same as above */
	sizeof(asn_DEF_Member_tags_6)
		/sizeof(asn_DEF_Member_tags_6[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_Member_6,
	1,	/* Single element */
	&asn_SPC_Member_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_cell_meas_reports_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_cell_meas_reports_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_cell_meas_reports_specs_5 = {
	sizeof(struct RXSigMeasReport__cell_meas_reports),
	offsetof(struct RXSigMeasReport__cell_meas_reports, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cell_meas_reports_5 = {
	"cell-meas-reports",
	"cell-meas-reports",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_cell_meas_reports_tags_5,
	sizeof(asn_DEF_cell_meas_reports_tags_5)
		/sizeof(asn_DEF_cell_meas_reports_tags_5[0]) - 1, /* 1 */
	asn_DEF_cell_meas_reports_tags_5,	/* Same as above */
	sizeof(asn_DEF_cell_meas_reports_tags_5)
		/sizeof(asn_DEF_cell_meas_reports_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_cell_meas_reports_5,
	1,	/* Single element */
	&asn_SPC_cell_meas_reports_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RXSigMeasReport_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RXSigMeasReport, crnti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_crnti_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RXSigMeasReport, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RXSigMeasReport, cell_meas_reports),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_cell_meas_reports_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cell-meas-reports"
		},
};
static const ber_tlv_tag_t asn_DEF_RXSigMeasReport_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RXSigMeasReport_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* cell-meas-reports */
};
asn_SEQUENCE_specifics_t asn_SPC_RXSigMeasReport_specs_1 = {
	sizeof(struct RXSigMeasReport),
	offsetof(struct RXSigMeasReport, _asn_ctx),
	asn_MAP_RXSigMeasReport_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RXSigMeasReport = {
	"RXSigMeasReport",
	"RXSigMeasReport",
	&asn_OP_SEQUENCE,
	asn_DEF_RXSigMeasReport_tags_1,
	sizeof(asn_DEF_RXSigMeasReport_tags_1)
		/sizeof(asn_DEF_RXSigMeasReport_tags_1[0]), /* 1 */
	asn_DEF_RXSigMeasReport_tags_1,	/* Same as above */
	sizeof(asn_DEF_RXSigMeasReport_tags_1)
		/sizeof(asn_DEF_RXSigMeasReport_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RXSigMeasReport_1,
	3,	/* Elements count */
	&asn_SPC_RXSigMeasReport_specs_1	/* Additional specs */
};

