/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_ScellDelete_H_
#define	_ScellDelete_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CRNTI.h"
#include "ECGI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PCI_ARFCN;

/* ScellDelete */
typedef struct ScellDelete {
	CRNTI_t	 crnti;
	ECGI_t	 ecgi;
	struct ScellDelete__scells_ind {
		A_SEQUENCE_OF(struct PCI_ARFCN) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} scells_ind;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScellDelete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScellDelete;
extern asn_SEQUENCE_specifics_t asn_SPC_ScellDelete_specs_1;
extern asn_TYPE_member_t asn_MBR_ScellDelete_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PCI-ARFCN.h"

#endif	/* _ScellDelete_H_ */
#include <asn_internal.h>
