/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "ScellAddStatus.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Member_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_Member_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_scells_ind_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PCI_ARFCN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_scells_ind_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_scells_ind_specs_4 = {
	sizeof(struct ScellAddStatus__scells_ind),
	offsetof(struct ScellAddStatus__scells_ind, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scells_ind_4 = {
	"scells-ind",
	"scells-ind",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_scells_ind_tags_4,
	sizeof(asn_DEF_scells_ind_tags_4)
		/sizeof(asn_DEF_scells_ind_tags_4[0]) - 1, /* 1 */
	asn_DEF_scells_ind_tags_4,	/* Same as above */
	sizeof(asn_DEF_scells_ind_tags_4)
		/sizeof(asn_DEF_scells_ind_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_scells_ind_4,
	1,	/* Single element */
	&asn_SPC_scells_ind_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_Member_value2enum_7[] = {
	{ 0,	7,	"success" },
	{ 1,	7,	"failure" }
};
static const unsigned int asn_MAP_Member_enum2value_7[] = {
	1,	/* failure(1) */
	0	/* success(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_Member_specs_7 = {
	asn_MAP_Member_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_Member_enum2value_7,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Member_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_7 = {
	"ENUMERATED",
	"ENUMERATED",
	&asn_OP_NativeEnumerated,
	asn_DEF_Member_tags_7,
	sizeof(asn_DEF_Member_tags_7)
		/sizeof(asn_DEF_Member_tags_7[0]), /* 1 */
	asn_DEF_Member_tags_7,	/* Same as above */
	sizeof(asn_DEF_Member_tags_7)
		/sizeof(asn_DEF_Member_tags_7[0]), /* 1 */
	{ &asn_OER_type_Member_constr_7, &asn_PER_type_Member_constr_7, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Member_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_status_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_Member_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_status_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_status_specs_6 = {
	sizeof(struct ScellAddStatus__status),
	offsetof(struct ScellAddStatus__status, _asn_ctx),
	1,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_status_6 = {
	"status",
	"status",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_status_tags_6,
	sizeof(asn_DEF_status_tags_6)
		/sizeof(asn_DEF_status_tags_6[0]) - 1, /* 1 */
	asn_DEF_status_tags_6,	/* Same as above */
	sizeof(asn_DEF_status_tags_6)
		/sizeof(asn_DEF_status_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_status_6,
	1,	/* Single element */
	&asn_SPC_status_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ScellAddStatus_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ScellAddStatus, crnti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ScellAddStatus, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ScellAddStatus, scells_ind),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_scells_ind_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"scells-ind"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ScellAddStatus, status),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_status_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"status"
		},
};
static const ber_tlv_tag_t asn_DEF_ScellAddStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ScellAddStatus_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* scells-ind */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* status */
};
asn_SEQUENCE_specifics_t asn_SPC_ScellAddStatus_specs_1 = {
	sizeof(struct ScellAddStatus),
	offsetof(struct ScellAddStatus, _asn_ctx),
	asn_MAP_ScellAddStatus_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ScellAddStatus = {
	"ScellAddStatus",
	"ScellAddStatus",
	&asn_OP_SEQUENCE,
	asn_DEF_ScellAddStatus_tags_1,
	sizeof(asn_DEF_ScellAddStatus_tags_1)
		/sizeof(asn_DEF_ScellAddStatus_tags_1[0]), /* 1 */
	asn_DEF_ScellAddStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_ScellAddStatus_tags_1)
		/sizeof(asn_DEF_ScellAddStatus_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ScellAddStatus_1,
	4,	/* Elements count */
	&asn_SPC_ScellAddStatus_specs_1	/* Additional specs */
};

