/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_SchedMeasReportPerCell_H_
#define	_SchedMeasReportPerCell_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "PRBUsage.h"
#include "QCI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SchedMeasReportPerCell */
typedef struct SchedMeasReportPerCell {
	ECGI_t	 ecgi;
	struct SchedMeasReportPerCell__qci_vals {
		A_SEQUENCE_OF(QCI_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} qci_vals;
	PRBUsage_t	 prb_usage_pcell;
	PRBUsage_t	 prb_usage_scell;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SchedMeasReportPerCell_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SchedMeasReportPerCell;
extern asn_SEQUENCE_specifics_t asn_SPC_SchedMeasReportPerCell_specs_1;
extern asn_TYPE_member_t asn_MBR_SchedMeasReportPerCell_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SchedMeasReportPerCell_H_ */
#include <asn_internal.h>
