/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "SchedMeasRepPerServCell.h"

static int
memb_qci_vals_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_mcs_dl_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_num_sched_ttis_dl_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_mcs_ul_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_num_sched_ttis_ul_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_rank_dl_1_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_rank_dl_2_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_qci_vals_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_qci_vals_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_mcs_dl_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_mcs_dl_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_num_sched_ttis_dl_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_num_sched_ttis_dl_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_mcs_ul_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_mcs_ul_constr_10 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_num_sched_ttis_ul_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_num_sched_ttis_ul_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_rank_dl_1_constr_14 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_rank_dl_1_constr_14 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_rank_dl_2_constr_16 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_rank_dl_2_constr_16 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_qci_vals_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_qci_vals_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_mcs_dl_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_mcs_dl_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_num_sched_ttis_dl_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_num_sched_ttis_dl_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_mcs_ul_constr_10 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_mcs_ul_constr_10 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_num_sched_ttis_ul_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_num_sched_ttis_ul_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_rank_dl_1_constr_14 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_rank_dl_1_constr_14 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_rank_dl_2_constr_16 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_rank_dl_2_constr_16 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_qci_vals_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_QCI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_qci_vals_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_qci_vals_specs_3 = {
	sizeof(struct SchedMeasRepPerServCell__qci_vals),
	offsetof(struct SchedMeasRepPerServCell__qci_vals, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_qci_vals_3 = {
	"qci-vals",
	"qci-vals",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_qci_vals_tags_3,
	sizeof(asn_DEF_qci_vals_tags_3)
		/sizeof(asn_DEF_qci_vals_tags_3[0]) - 1, /* 1 */
	asn_DEF_qci_vals_tags_3,	/* Same as above */
	sizeof(asn_DEF_qci_vals_tags_3)
		/sizeof(asn_DEF_qci_vals_tags_3[0]), /* 2 */
	{ &asn_OER_type_qci_vals_constr_3, &asn_PER_type_qci_vals_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_qci_vals_3,
	1,	/* Single element */
	&asn_SPC_qci_vals_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_mcs_dl_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_mcs_dl_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_mcs_dl_specs_6 = {
	sizeof(struct SchedMeasRepPerServCell__mcs_dl),
	offsetof(struct SchedMeasRepPerServCell__mcs_dl, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mcs_dl_6 = {
	"mcs-dl",
	"mcs-dl",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_mcs_dl_tags_6,
	sizeof(asn_DEF_mcs_dl_tags_6)
		/sizeof(asn_DEF_mcs_dl_tags_6[0]) - 1, /* 1 */
	asn_DEF_mcs_dl_tags_6,	/* Same as above */
	sizeof(asn_DEF_mcs_dl_tags_6)
		/sizeof(asn_DEF_mcs_dl_tags_6[0]), /* 2 */
	{ &asn_OER_type_mcs_dl_constr_6, &asn_PER_type_mcs_dl_constr_6, SEQUENCE_OF_constraint },
	asn_MBR_mcs_dl_6,
	1,	/* Single element */
	&asn_SPC_mcs_dl_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_num_sched_ttis_dl_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_num_sched_ttis_dl_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_num_sched_ttis_dl_specs_8 = {
	sizeof(struct SchedMeasRepPerServCell__num_sched_ttis_dl),
	offsetof(struct SchedMeasRepPerServCell__num_sched_ttis_dl, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_num_sched_ttis_dl_8 = {
	"num-sched-ttis-dl",
	"num-sched-ttis-dl",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_num_sched_ttis_dl_tags_8,
	sizeof(asn_DEF_num_sched_ttis_dl_tags_8)
		/sizeof(asn_DEF_num_sched_ttis_dl_tags_8[0]) - 1, /* 1 */
	asn_DEF_num_sched_ttis_dl_tags_8,	/* Same as above */
	sizeof(asn_DEF_num_sched_ttis_dl_tags_8)
		/sizeof(asn_DEF_num_sched_ttis_dl_tags_8[0]), /* 2 */
	{ &asn_OER_type_num_sched_ttis_dl_constr_8, &asn_PER_type_num_sched_ttis_dl_constr_8, SEQUENCE_OF_constraint },
	asn_MBR_num_sched_ttis_dl_8,
	1,	/* Single element */
	&asn_SPC_num_sched_ttis_dl_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_mcs_ul_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_mcs_ul_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_mcs_ul_specs_10 = {
	sizeof(struct SchedMeasRepPerServCell__mcs_ul),
	offsetof(struct SchedMeasRepPerServCell__mcs_ul, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mcs_ul_10 = {
	"mcs-ul",
	"mcs-ul",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_mcs_ul_tags_10,
	sizeof(asn_DEF_mcs_ul_tags_10)
		/sizeof(asn_DEF_mcs_ul_tags_10[0]) - 1, /* 1 */
	asn_DEF_mcs_ul_tags_10,	/* Same as above */
	sizeof(asn_DEF_mcs_ul_tags_10)
		/sizeof(asn_DEF_mcs_ul_tags_10[0]), /* 2 */
	{ &asn_OER_type_mcs_ul_constr_10, &asn_PER_type_mcs_ul_constr_10, SEQUENCE_OF_constraint },
	asn_MBR_mcs_ul_10,
	1,	/* Single element */
	&asn_SPC_mcs_ul_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_num_sched_ttis_ul_12[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_num_sched_ttis_ul_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_num_sched_ttis_ul_specs_12 = {
	sizeof(struct SchedMeasRepPerServCell__num_sched_ttis_ul),
	offsetof(struct SchedMeasRepPerServCell__num_sched_ttis_ul, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_num_sched_ttis_ul_12 = {
	"num-sched-ttis-ul",
	"num-sched-ttis-ul",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_num_sched_ttis_ul_tags_12,
	sizeof(asn_DEF_num_sched_ttis_ul_tags_12)
		/sizeof(asn_DEF_num_sched_ttis_ul_tags_12[0]) - 1, /* 1 */
	asn_DEF_num_sched_ttis_ul_tags_12,	/* Same as above */
	sizeof(asn_DEF_num_sched_ttis_ul_tags_12)
		/sizeof(asn_DEF_num_sched_ttis_ul_tags_12[0]), /* 2 */
	{ &asn_OER_type_num_sched_ttis_ul_constr_12, &asn_PER_type_num_sched_ttis_ul_constr_12, SEQUENCE_OF_constraint },
	asn_MBR_num_sched_ttis_ul_12,
	1,	/* Single element */
	&asn_SPC_num_sched_ttis_ul_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_rank_dl_1_14[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_rank_dl_1_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_rank_dl_1_specs_14 = {
	sizeof(struct SchedMeasRepPerServCell__rank_dl_1),
	offsetof(struct SchedMeasRepPerServCell__rank_dl_1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rank_dl_1_14 = {
	"rank-dl-1",
	"rank-dl-1",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_rank_dl_1_tags_14,
	sizeof(asn_DEF_rank_dl_1_tags_14)
		/sizeof(asn_DEF_rank_dl_1_tags_14[0]) - 1, /* 1 */
	asn_DEF_rank_dl_1_tags_14,	/* Same as above */
	sizeof(asn_DEF_rank_dl_1_tags_14)
		/sizeof(asn_DEF_rank_dl_1_tags_14[0]), /* 2 */
	{ &asn_OER_type_rank_dl_1_constr_14, &asn_PER_type_rank_dl_1_constr_14, SEQUENCE_OF_constraint },
	asn_MBR_rank_dl_1_14,
	1,	/* Single element */
	&asn_SPC_rank_dl_1_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_rank_dl_2_16[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_rank_dl_2_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_rank_dl_2_specs_16 = {
	sizeof(struct SchedMeasRepPerServCell__rank_dl_2),
	offsetof(struct SchedMeasRepPerServCell__rank_dl_2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rank_dl_2_16 = {
	"rank-dl-2",
	"rank-dl-2",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_rank_dl_2_tags_16,
	sizeof(asn_DEF_rank_dl_2_tags_16)
		/sizeof(asn_DEF_rank_dl_2_tags_16[0]) - 1, /* 1 */
	asn_DEF_rank_dl_2_tags_16,	/* Same as above */
	sizeof(asn_DEF_rank_dl_2_tags_16)
		/sizeof(asn_DEF_rank_dl_2_tags_16[0]), /* 2 */
	{ &asn_OER_type_rank_dl_2_constr_16, &asn_PER_type_rank_dl_2_constr_16, SEQUENCE_OF_constraint },
	asn_MBR_rank_dl_2_16,
	1,	/* Single element */
	&asn_SPC_rank_dl_2_specs_16	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SchedMeasRepPerServCell_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasRepPerServCell, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasRepPerServCell, qci_vals),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_qci_vals_3,
		0,
		{ &asn_OER_memb_qci_vals_constr_3, &asn_PER_memb_qci_vals_constr_3,  memb_qci_vals_constraint_1 },
		0, 0, /* No default value */
		"qci-vals"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasRepPerServCell, prb_usage),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRBUsage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prb-usage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasRepPerServCell, mcs_dl),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_mcs_dl_6,
		0,
		{ &asn_OER_memb_mcs_dl_constr_6, &asn_PER_memb_mcs_dl_constr_6,  memb_mcs_dl_constraint_1 },
		0, 0, /* No default value */
		"mcs-dl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasRepPerServCell, num_sched_ttis_dl),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_num_sched_ttis_dl_8,
		0,
		{ &asn_OER_memb_num_sched_ttis_dl_constr_8, &asn_PER_memb_num_sched_ttis_dl_constr_8,  memb_num_sched_ttis_dl_constraint_1 },
		0, 0, /* No default value */
		"num-sched-ttis-dl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasRepPerServCell, mcs_ul),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_mcs_ul_10,
		0,
		{ &asn_OER_memb_mcs_ul_constr_10, &asn_PER_memb_mcs_ul_constr_10,  memb_mcs_ul_constraint_1 },
		0, 0, /* No default value */
		"mcs-ul"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasRepPerServCell, num_sched_ttis_ul),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_num_sched_ttis_ul_12,
		0,
		{ &asn_OER_memb_num_sched_ttis_ul_constr_12, &asn_PER_memb_num_sched_ttis_ul_constr_12,  memb_num_sched_ttis_ul_constraint_1 },
		0, 0, /* No default value */
		"num-sched-ttis-ul"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasRepPerServCell, rank_dl_1),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_rank_dl_1_14,
		0,
		{ &asn_OER_memb_rank_dl_1_constr_14, &asn_PER_memb_rank_dl_1_constr_14,  memb_rank_dl_1_constraint_1 },
		0, 0, /* No default value */
		"rank-dl-1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasRepPerServCell, rank_dl_2),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_rank_dl_2_16,
		0,
		{ &asn_OER_memb_rank_dl_2_constr_16, &asn_PER_memb_rank_dl_2_constr_16,  memb_rank_dl_2_constraint_1 },
		0, 0, /* No default value */
		"rank-dl-2"
		},
};
static const ber_tlv_tag_t asn_DEF_SchedMeasRepPerServCell_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SchedMeasRepPerServCell_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* qci-vals */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* prb-usage */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mcs-dl */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* num-sched-ttis-dl */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* mcs-ul */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* num-sched-ttis-ul */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* rank-dl-1 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* rank-dl-2 */
};
asn_SEQUENCE_specifics_t asn_SPC_SchedMeasRepPerServCell_specs_1 = {
	sizeof(struct SchedMeasRepPerServCell),
	offsetof(struct SchedMeasRepPerServCell, _asn_ctx),
	asn_MAP_SchedMeasRepPerServCell_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	9,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SchedMeasRepPerServCell = {
	"SchedMeasRepPerServCell",
	"SchedMeasRepPerServCell",
	&asn_OP_SEQUENCE,
	asn_DEF_SchedMeasRepPerServCell_tags_1,
	sizeof(asn_DEF_SchedMeasRepPerServCell_tags_1)
		/sizeof(asn_DEF_SchedMeasRepPerServCell_tags_1[0]), /* 1 */
	asn_DEF_SchedMeasRepPerServCell_tags_1,	/* Same as above */
	sizeof(asn_DEF_SchedMeasRepPerServCell_tags_1)
		/sizeof(asn_DEF_SchedMeasRepPerServCell_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SchedMeasRepPerServCell_1,
	9,	/* Elements count */
	&asn_SPC_SchedMeasRepPerServCell_specs_1	/* Additional specs */
};

