/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "SchedMeasReportPerCell.h"

static int
memb_qci_vals_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 9)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_qci_vals_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_type_qci_vals_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_qci_vals_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..9)) */};
static asn_per_constraints_t asn_PER_memb_qci_vals_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  9 }	/* (SIZE(1..9)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_qci_vals_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_QCI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_qci_vals_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_qci_vals_specs_3 = {
	sizeof(struct SchedMeasReportPerCell__qci_vals),
	offsetof(struct SchedMeasReportPerCell__qci_vals, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_qci_vals_3 = {
	"qci-vals",
	"qci-vals",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_qci_vals_tags_3,
	sizeof(asn_DEF_qci_vals_tags_3)
		/sizeof(asn_DEF_qci_vals_tags_3[0]) - 1, /* 1 */
	asn_DEF_qci_vals_tags_3,	/* Same as above */
	sizeof(asn_DEF_qci_vals_tags_3)
		/sizeof(asn_DEF_qci_vals_tags_3[0]), /* 2 */
	{ &asn_OER_type_qci_vals_constr_3, &asn_PER_type_qci_vals_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_qci_vals_3,
	1,	/* Single element */
	&asn_SPC_qci_vals_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SchedMeasReportPerCell_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasReportPerCell, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasReportPerCell, qci_vals),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_qci_vals_3,
		0,
		{ &asn_OER_memb_qci_vals_constr_3, &asn_PER_memb_qci_vals_constr_3,  memb_qci_vals_constraint_1 },
		0, 0, /* No default value */
		"qci-vals"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasReportPerCell, prb_usage_pcell),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRBUsage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prb-usage-pcell"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SchedMeasReportPerCell, prb_usage_scell),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRBUsage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prb-usage-scell"
		},
};
static const ber_tlv_tag_t asn_DEF_SchedMeasReportPerCell_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SchedMeasReportPerCell_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* qci-vals */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* prb-usage-pcell */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* prb-usage-scell */
};
asn_SEQUENCE_specifics_t asn_SPC_SchedMeasReportPerCell_specs_1 = {
	sizeof(struct SchedMeasReportPerCell),
	offsetof(struct SchedMeasReportPerCell, _asn_ctx),
	asn_MAP_SchedMeasReportPerCell_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SchedMeasReportPerCell = {
	"SchedMeasReportPerCell",
	"SchedMeasReportPerCell",
	&asn_OP_SEQUENCE,
	asn_DEF_SchedMeasReportPerCell_tags_1,
	sizeof(asn_DEF_SchedMeasReportPerCell_tags_1)
		/sizeof(asn_DEF_SchedMeasReportPerCell_tags_1[0]), /* 1 */
	asn_DEF_SchedMeasReportPerCell_tags_1,	/* Same as above */
	sizeof(asn_DEF_SchedMeasReportPerCell_tags_1)
		/sizeof(asn_DEF_SchedMeasReportPerCell_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SchedMeasReportPerCell_1,
	4,	/* Elements count */
	&asn_SPC_SchedMeasReportPerCell_specs_1	/* Additional specs */
};

