/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_SchedMeasRepPerServCell_H_
#define	_SchedMeasRepPerServCell_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include "PRBUsage.h"
#include "QCI.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SchedMeasRepPerServCell */
typedef struct SchedMeasRepPerServCell {
	ECGI_t	 ecgi;
	struct SchedMeasRepPerServCell__qci_vals {
		A_SEQUENCE_OF(QCI_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} qci_vals;
	PRBUsage_t	 prb_usage;
	struct SchedMeasRepPerServCell__mcs_dl {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} mcs_dl;
	struct SchedMeasRepPerServCell__num_sched_ttis_dl {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} num_sched_ttis_dl;
	struct SchedMeasRepPerServCell__mcs_ul {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} mcs_ul;
	struct SchedMeasRepPerServCell__num_sched_ttis_ul {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} num_sched_ttis_ul;
	struct SchedMeasRepPerServCell__rank_dl_1 {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rank_dl_1;
	struct SchedMeasRepPerServCell__rank_dl_2 {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rank_dl_2;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SchedMeasRepPerServCell_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SchedMeasRepPerServCell;
extern asn_SEQUENCE_specifics_t asn_SPC_SchedMeasRepPerServCell_specs_1;
extern asn_TYPE_member_t asn_MBR_SchedMeasRepPerServCell_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _SchedMeasRepPerServCell_H_ */
#include <asn_internal.h>
