/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_SeNBAddStatus_H_
#define	_SeNBAddStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CRNTI.h"
#include "ECGI.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SeNBAddStatus__status {
	SeNBAddStatus__status_success	= 0,
	SeNBAddStatus__status_failure	= 1
} e_SeNBAddStatus__status;

/* SeNBAddStatus */
typedef struct SeNBAddStatus {
	CRNTI_t	 crnti;
	ECGI_t	 ecgi;
	long	 status;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SeNBAddStatus_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_status_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SeNBAddStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_SeNBAddStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_SeNBAddStatus_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SeNBAddStatus_H_ */
#include <asn_internal.h>
