/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "SeNBAddStatus.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_status_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_status_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_status_value2enum_4[] = {
	{ 0,	7,	"success" },
	{ 1,	7,	"failure" }
};
static const unsigned int asn_MAP_status_enum2value_4[] = {
	1,	/* failure(1) */
	0	/* success(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_status_specs_4 = {
	asn_MAP_status_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_status_enum2value_4,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_status_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_status_4 = {
	"status",
	"status",
	&asn_OP_NativeEnumerated,
	asn_DEF_status_tags_4,
	sizeof(asn_DEF_status_tags_4)
		/sizeof(asn_DEF_status_tags_4[0]) - 1, /* 1 */
	asn_DEF_status_tags_4,	/* Same as above */
	sizeof(asn_DEF_status_tags_4)
		/sizeof(asn_DEF_status_tags_4[0]), /* 2 */
	{ &asn_OER_type_status_constr_4, &asn_PER_type_status_constr_4, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_status_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SeNBAddStatus_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SeNBAddStatus, crnti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SeNBAddStatus, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SeNBAddStatus, status),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_status_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"status"
		},
};
static const ber_tlv_tag_t asn_DEF_SeNBAddStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SeNBAddStatus_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* status */
};
asn_SEQUENCE_specifics_t asn_SPC_SeNBAddStatus_specs_1 = {
	sizeof(struct SeNBAddStatus),
	offsetof(struct SeNBAddStatus, _asn_ctx),
	asn_MAP_SeNBAddStatus_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SeNBAddStatus = {
	"SeNBAddStatus",
	"SeNBAddStatus",
	&asn_OP_SEQUENCE,
	asn_DEF_SeNBAddStatus_tags_1,
	sizeof(asn_DEF_SeNBAddStatus_tags_1)
		/sizeof(asn_DEF_SeNBAddStatus_tags_1[0]), /* 1 */
	asn_DEF_SeNBAddStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_SeNBAddStatus_tags_1)
		/sizeof(asn_DEF_SeNBAddStatus_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SeNBAddStatus_1,
	3,	/* Elements count */
	&asn_SPC_SeNBAddStatus_specs_1	/* Additional specs */
};

