/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_SeNBAdd_H_
#define	_SeNBAdd_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CRNTI.h"
#include "ECGI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SeNBAdd */
typedef struct SeNBAdd {
	CRNTI_t	 crnti;
	ECGI_t	 m_ecgi;
	ECGI_t	 s_ecgi;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SeNBAdd_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeNBAdd;
extern asn_SEQUENCE_specifics_t asn_SPC_SeNBAdd_specs_1;
extern asn_TYPE_member_t asn_MBR_SeNBAdd_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SeNBAdd_H_ */
#include <asn_internal.h>
