/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "TrafficSplitConfig.h"

static asn_TYPE_member_t asn_MBR_traffic_split_percent_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TrafficSplitPercentage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_traffic_split_percent_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_traffic_split_percent_specs_4 = {
	sizeof(struct TrafficSplitConfig__traffic_split_percent),
	offsetof(struct TrafficSplitConfig__traffic_split_percent, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_traffic_split_percent_4 = {
	"traffic-split-percent",
	"traffic-split-percent",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_traffic_split_percent_tags_4,
	sizeof(asn_DEF_traffic_split_percent_tags_4)
		/sizeof(asn_DEF_traffic_split_percent_tags_4[0]) - 1, /* 1 */
	asn_DEF_traffic_split_percent_tags_4,	/* Same as above */
	sizeof(asn_DEF_traffic_split_percent_tags_4)
		/sizeof(asn_DEF_traffic_split_percent_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_traffic_split_percent_4,
	1,	/* Single element */
	&asn_SPC_traffic_split_percent_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_TrafficSplitConfig_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TrafficSplitConfig, crnti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TrafficSplitConfig, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TrafficSplitConfig, traffic_split_percent),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_traffic_split_percent_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"traffic-split-percent"
		},
};
static const ber_tlv_tag_t asn_DEF_TrafficSplitConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TrafficSplitConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* traffic-split-percent */
};
asn_SEQUENCE_specifics_t asn_SPC_TrafficSplitConfig_specs_1 = {
	sizeof(struct TrafficSplitConfig),
	offsetof(struct TrafficSplitConfig, _asn_ctx),
	asn_MAP_TrafficSplitConfig_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TrafficSplitConfig = {
	"TrafficSplitConfig",
	"TrafficSplitConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_TrafficSplitConfig_tags_1,
	sizeof(asn_DEF_TrafficSplitConfig_tags_1)
		/sizeof(asn_DEF_TrafficSplitConfig_tags_1[0]), /* 1 */
	asn_DEF_TrafficSplitConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_TrafficSplitConfig_tags_1)
		/sizeof(asn_DEF_TrafficSplitConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TrafficSplitConfig_1,
	3,	/* Elements count */
	&asn_SPC_TrafficSplitConfig_specs_1	/* Additional specs */
};

