/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_TrafficSplitPercentage_H_
#define	_TrafficSplitPercentage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECGI.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TrafficSplitPercentage */
typedef struct TrafficSplitPercentage {
	ECGI_t	 ecgi;
	long	*traffic_percent_dl	/* OPTIONAL */;
	long	*traffic_percent_ul	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrafficSplitPercentage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrafficSplitPercentage;
extern asn_SEQUENCE_specifics_t asn_SPC_TrafficSplitPercentage_specs_1;
extern asn_TYPE_member_t asn_MBR_TrafficSplitPercentage_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _TrafficSplitPercentage_H_ */
#include <asn_internal.h>
