/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "UEAdmissionResponse.h"

asn_TYPE_member_t asn_MBR_UEAdmissionResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UEAdmissionResponse, crnti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEAdmissionResponse, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEAdmissionResponse, adm_est_response),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdmEstResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"adm-est-response"
		},
};
static const ber_tlv_tag_t asn_DEF_UEAdmissionResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UEAdmissionResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* adm-est-response */
};
asn_SEQUENCE_specifics_t asn_SPC_UEAdmissionResponse_specs_1 = {
	sizeof(struct UEAdmissionResponse),
	offsetof(struct UEAdmissionResponse, _asn_ctx),
	asn_MAP_UEAdmissionResponse_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UEAdmissionResponse = {
	"UEAdmissionResponse",
	"UEAdmissionResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_UEAdmissionResponse_tags_1,
	sizeof(asn_DEF_UEAdmissionResponse_tags_1)
		/sizeof(asn_DEF_UEAdmissionResponse_tags_1[0]), /* 1 */
	asn_DEF_UEAdmissionResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_UEAdmissionResponse_tags_1)
		/sizeof(asn_DEF_UEAdmissionResponse_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UEAdmissionResponse_1,
	3,	/* Elements count */
	&asn_SPC_UEAdmissionResponse_specs_1	/* Additional specs */
};

