/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_UEAdmissionStatus_H_
#define	_UEAdmissionStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CRNTI.h"
#include "ECGI.h"
#include "AdmEstStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UEAdmissionStatus */
typedef struct UEAdmissionStatus {
	CRNTI_t	 crnti;
	ECGI_t	 ecgi;
	AdmEstStatus_t	 adm_est_status;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEAdmissionStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEAdmissionStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_UEAdmissionStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_UEAdmissionStatus_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UEAdmissionStatus_H_ */
#include <asn_internal.h>
