/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "UEAMBR.h"

asn_TYPE_member_t asn_MBR_UEAMBR_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UEAMBR, ambr_dl),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ambr-dl"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEAMBR, ambr_ul),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ambr-ul"
		},
};
static const ber_tlv_tag_t asn_DEF_UEAMBR_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UEAMBR_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ambr-dl */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ambr-ul */
};
asn_SEQUENCE_specifics_t asn_SPC_UEAMBR_specs_1 = {
	sizeof(struct UEAMBR),
	offsetof(struct UEAMBR, _asn_ctx),
	asn_MAP_UEAMBR_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UEAMBR = {
	"UEAMBR",
	"UEAMBR",
	&asn_OP_SEQUENCE,
	asn_DEF_UEAMBR_tags_1,
	sizeof(asn_DEF_UEAMBR_tags_1)
		/sizeof(asn_DEF_UEAMBR_tags_1[0]), /* 1 */
	asn_DEF_UEAMBR_tags_1,	/* Same as above */
	sizeof(asn_DEF_UEAMBR_tags_1)
		/sizeof(asn_DEF_UEAMBR_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UEAMBR_1,
	2,	/* Elements count */
	&asn_SPC_UEAMBR_specs_1	/* Additional specs */
};

