/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_UEContextUpdate_H_
#define	_UEContextUpdate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CRNTI.h"
#include "ECGI.h"
#include "MME-UE-S1AP-ID.h"
#include "ENB-UE-S1AP-ID.h"
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UEContextUpdate */
typedef struct UEContextUpdate {
	CRNTI_t	 crnti;
	ECGI_t	 ecgi;
	MME_UE_S1AP_ID_t	 mME_UE_S1AP_ID;
	ENB_UE_S1AP_ID_t	 eNB_UE_S1AP_ID;
	UTF8String_t	*imsi	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEContextUpdate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEContextUpdate;
extern asn_SEQUENCE_specifics_t asn_SPC_UEContextUpdate_specs_1;
extern asn_TYPE_member_t asn_MBR_UEContextUpdate_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _UEContextUpdate_H_ */
#include <asn_internal.h>
