/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "UEContextUpdate.h"

asn_TYPE_member_t asn_MBR_UEContextUpdate_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UEContextUpdate, crnti),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CRNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crnti"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEContextUpdate, ecgi),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ECGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ecgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEContextUpdate, mME_UE_S1AP_ID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MME_UE_S1AP_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mME-UE-S1AP-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEContextUpdate, eNB_UE_S1AP_ID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ENB_UE_S1AP_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eNB-UE-S1AP-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct UEContextUpdate, imsi),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"imsi"
		},
};
static const int asn_MAP_UEContextUpdate_oms_1[] = { 4 };
static const ber_tlv_tag_t asn_DEF_UEContextUpdate_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UEContextUpdate_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crnti */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ecgi */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* mME-UE-S1AP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* eNB-UE-S1AP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* imsi */
};
asn_SEQUENCE_specifics_t asn_SPC_UEContextUpdate_specs_1 = {
	sizeof(struct UEContextUpdate),
	offsetof(struct UEContextUpdate, _asn_ctx),
	asn_MAP_UEContextUpdate_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_UEContextUpdate_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UEContextUpdate = {
	"UEContextUpdate",
	"UEContextUpdate",
	&asn_OP_SEQUENCE,
	asn_DEF_UEContextUpdate_tags_1,
	sizeof(asn_DEF_UEContextUpdate_tags_1)
		/sizeof(asn_DEF_UEContextUpdate_tags_1[0]), /* 1 */
	asn_DEF_UEContextUpdate_tags_1,	/* Same as above */
	sizeof(asn_DEF_UEContextUpdate_tags_1)
		/sizeof(asn_DEF_UEContextUpdate_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UEContextUpdate_1,
	5,	/* Elements count */
	&asn_SPC_UEContextUpdate_specs_1	/* Additional specs */
};

