/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_UEReconfigInd_H_
#define	_UEReconfigInd_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CRNTI.h"
#include "ECGI.h"
#include "ReconfIndReason.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UEReconfigInd */
typedef struct UEReconfigInd {
	CRNTI_t	 crnti_old;
	ECGI_t	 ecgi;
	CRNTI_t	 crnti_new;
	ReconfIndReason_t	 reconfig_cause;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEReconfigInd_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEReconfigInd;
extern asn_SEQUENCE_specifics_t asn_SPC_UEReconfigInd_specs_1;
extern asn_TYPE_member_t asn_MBR_UEReconfigInd_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _UEReconfigInd_H_ */
#include <asn_internal.h>
