/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-API"
 * 	found in "../xranc-sb-api/xRAN-API-IEs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_XICIC_PA_H_
#define	_XICIC_PA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum XICIC_PA {
	XICIC_PA_dB_minus6	= 0,
	XICIC_PA_dB_minus4dot77	= 1,
	XICIC_PA_dB_minus3	= 2,
	XICIC_PA_dB_minus1dot77	= 3,
	XICIC_PA_dB_0	= 4,
	XICIC_PA_dB_1	= 5,
	XICIC_PA_dB_2	= 6,
	XICIC_PA_dB_3	= 7
	/*
	 * Enumeration is extensible
	 */
} e_XICIC_PA;

/* XICIC-PA */
typedef long	 XICIC_PA_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_XICIC_PA_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_XICIC_PA;
extern const asn_INTEGER_specifics_t asn_SPC_XICIC_PA_specs_1;
asn_struct_free_f XICIC_PA_free;
asn_struct_print_f XICIC_PA_print;
asn_constr_check_f XICIC_PA_constraint;
ber_type_decoder_f XICIC_PA_decode_ber;
der_type_encoder_f XICIC_PA_encode_der;
xer_type_decoder_f XICIC_PA_decode_xer;
xer_type_encoder_f XICIC_PA_encode_xer;
oer_type_decoder_f XICIC_PA_decode_oer;
oer_type_encoder_f XICIC_PA_encode_oer;
per_type_decoder_f XICIC_PA_decode_uper;
per_type_encoder_f XICIC_PA_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _XICIC_PA_H_ */
#include <asn_internal.h>
