/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_XRANCPDUBody_H_
#define	_XRANCPDUBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CellConfigRequest.h"
#include "CellConfigReport.h"
#include "UEAdmissionRequest.h"
#include "UEAdmissionResponse.h"
#include "UEAdmissionStatus.h"
#include "UEContextUpdate.h"
#include "UEReconfigInd.h"
#include "UEReleaseInd.h"
#include "BearerAdmissionRequest.h"
#include "BearerAdmissionResponse.h"
#include "BearerAdmissionStatus.h"
#include "BearerReleaseInd.h"
#include "HORequest.h"
#include "HOFailure.h"
#include "HOComplete.h"
#include "RXSigMeasReport.h"
#include "L2MeasConfig.h"
#include "RadioMeasReportPerUE.h"
#include "RadioMeasReportPerCell.h"
#include "SchedMeasReportPerUE.h"
#include "SchedMeasReportPerCell.h"
#include "PDCPMeasReportPerUe.h"
#include "UECapabilityEnquiry.h"
#include "UECapabilityInfo.h"
#include "ScellAdd.h"
#include "ScellAddStatus.h"
#include "ScellDelete.h"
#include "RRMConfig.h"
#include "RRMConfigStatus.h"
#include "SeNBAdd.h"
#include "SeNBAddStatus.h"
#include "SeNBDelete.h"
#include "TrafficSplitConfig.h"
#include "HOCause.h"
#include "RRCMeasConfig.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum XRANCPDUBody_PR {
	XRANCPDUBody_PR_NOTHING,	/* No components present */
	XRANCPDUBody_PR_cellConfigRequest,
	XRANCPDUBody_PR_cellConfigReport,
	XRANCPDUBody_PR_uEAdmissionRequest,
	XRANCPDUBody_PR_uEAdmissionResponse,
	XRANCPDUBody_PR_uEAdmissionStatus,
	XRANCPDUBody_PR_uEContextUpdate,
	XRANCPDUBody_PR_uEReconfigInd,
	XRANCPDUBody_PR_uEReleaseInd,
	XRANCPDUBody_PR_bearerAdmissionRequest,
	XRANCPDUBody_PR_bearerAdmissionResponse,
	XRANCPDUBody_PR_bearerAdmissionStatus,
	XRANCPDUBody_PR_bearerReleaseInd,
	XRANCPDUBody_PR_hORequest,
	XRANCPDUBody_PR_hOFailure,
	XRANCPDUBody_PR_hOComplete,
	XRANCPDUBody_PR_rXSigMeasReport,
	XRANCPDUBody_PR_l2MeasConfig,
	XRANCPDUBody_PR_radioMeasReportPerUE,
	XRANCPDUBody_PR_radioMeasReportPerCell,
	XRANCPDUBody_PR_schedMeasReportPerUE,
	XRANCPDUBody_PR_schedMeasReportPerCell,
	XRANCPDUBody_PR_pDCPMeasReportPerUe,
	XRANCPDUBody_PR_uECapabilityEnquiry,
	XRANCPDUBody_PR_uECapabilityInfo,
	XRANCPDUBody_PR_scellAdd,
	XRANCPDUBody_PR_scellAddStatus,
	XRANCPDUBody_PR_scellDelete,
	XRANCPDUBody_PR_rRMConfig,
	XRANCPDUBody_PR_rRMConfigStatus,
	XRANCPDUBody_PR_seNBAdd,
	XRANCPDUBody_PR_seNBAddStatus,
	XRANCPDUBody_PR_seNBDelete,
	XRANCPDUBody_PR_trafficSplitConfig,
	XRANCPDUBody_PR_hOCause,
	XRANCPDUBody_PR_rRCMeasConfig
	/* Extensions may appear below */
	
} XRANCPDUBody_PR;

/* XRANCPDUBody */
typedef struct XRANCPDUBody {
	XRANCPDUBody_PR present;
	union XRANCPDUBody_u {
		CellConfigRequest_t	 cellConfigRequest;
		CellConfigReport_t	 cellConfigReport;
		UEAdmissionRequest_t	 uEAdmissionRequest;
		UEAdmissionResponse_t	 uEAdmissionResponse;
		UEAdmissionStatus_t	 uEAdmissionStatus;
		UEContextUpdate_t	 uEContextUpdate;
		UEReconfigInd_t	 uEReconfigInd;
		UEReleaseInd_t	 uEReleaseInd;
		BearerAdmissionRequest_t	 bearerAdmissionRequest;
		BearerAdmissionResponse_t	 bearerAdmissionResponse;
		BearerAdmissionStatus_t	 bearerAdmissionStatus;
		BearerReleaseInd_t	 bearerReleaseInd;
		HORequest_t	 hORequest;
		HOFailure_t	 hOFailure;
		HOComplete_t	 hOComplete;
		RXSigMeasReport_t	 rXSigMeasReport;
		L2MeasConfig_t	 l2MeasConfig;
		RadioMeasReportPerUE_t	 radioMeasReportPerUE;
		RadioMeasReportPerCell_t	 radioMeasReportPerCell;
		SchedMeasReportPerUE_t	 schedMeasReportPerUE;
		SchedMeasReportPerCell_t	 schedMeasReportPerCell;
		PDCPMeasReportPerUe_t	 pDCPMeasReportPerUe;
		UECapabilityEnquiry_t	 uECapabilityEnquiry;
		UECapabilityInfo_t	 uECapabilityInfo;
		ScellAdd_t	 scellAdd;
		ScellAddStatus_t	 scellAddStatus;
		ScellDelete_t	 scellDelete;
		RRMConfig_t	 rRMConfig;
		RRMConfigStatus_t	 rRMConfigStatus;
		SeNBAdd_t	 seNBAdd;
		SeNBAddStatus_t	 seNBAddStatus;
		SeNBDelete_t	 seNBDelete;
		TrafficSplitConfig_t	 trafficSplitConfig;
		HOCause_t	 hOCause;
		RRCMeasConfig_t	 rRCMeasConfig;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} XRANCPDUBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_XRANCPDUBody;
extern asn_CHOICE_specifics_t asn_SPC_XRANCPDUBody_specs_1;
extern asn_TYPE_member_t asn_MBR_XRANCPDUBody_1[35];
extern asn_per_constraints_t asn_PER_type_XRANCPDUBody_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _XRANCPDUBody_H_ */
#include <asn_internal.h>
