/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "XRANCPDUBody.h"

static asn_oer_constraints_t asn_OER_type_XRANCPDUBody_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_XRANCPDUBody_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  6,  6,  0,  34 }	/* (0..34,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_XRANCPDUBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.cellConfigRequest),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellConfigRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellConfigRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.cellConfigReport),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellConfigReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellConfigReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.uEAdmissionRequest),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEAdmissionRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uEAdmissionRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.uEAdmissionResponse),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEAdmissionResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uEAdmissionResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.uEAdmissionStatus),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEAdmissionStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uEAdmissionStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.uEContextUpdate),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEContextUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uEContextUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.uEReconfigInd),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEReconfigInd,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uEReconfigInd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.uEReleaseInd),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEReleaseInd,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uEReleaseInd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.bearerAdmissionRequest),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BearerAdmissionRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bearerAdmissionRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.bearerAdmissionResponse),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BearerAdmissionResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bearerAdmissionResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.bearerAdmissionStatus),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BearerAdmissionStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bearerAdmissionStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.bearerReleaseInd),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BearerReleaseInd,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bearerReleaseInd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.hORequest),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HORequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hORequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.hOFailure),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HOFailure,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hOFailure"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.hOComplete),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HOComplete,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hOComplete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.rXSigMeasReport),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RXSigMeasReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rXSigMeasReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.l2MeasConfig),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_L2MeasConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"l2MeasConfig"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.radioMeasReportPerUE),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioMeasReportPerUE,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioMeasReportPerUE"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.radioMeasReportPerCell),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioMeasReportPerCell,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioMeasReportPerCell"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.schedMeasReportPerUE),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SchedMeasReportPerUE,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"schedMeasReportPerUE"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.schedMeasReportPerCell),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SchedMeasReportPerCell,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"schedMeasReportPerCell"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.pDCPMeasReportPerUe),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDCPMeasReportPerUe,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pDCPMeasReportPerUe"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.uECapabilityEnquiry),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UECapabilityEnquiry,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uECapabilityEnquiry"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.uECapabilityInfo),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UECapabilityInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uECapabilityInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.scellAdd),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ScellAdd,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"scellAdd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.scellAddStatus),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ScellAddStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"scellAddStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.scellDelete),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ScellDelete,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"scellDelete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.rRMConfig),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRMConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rRMConfig"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.rRMConfigStatus),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRMConfigStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rRMConfigStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.seNBAdd),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeNBAdd,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"seNBAdd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.seNBAddStatus),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeNBAddStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"seNBAddStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.seNBDelete),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeNBDelete,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"seNBDelete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.trafficSplitConfig),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrafficSplitConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"trafficSplitConfig"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.hOCause),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HOCause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hOCause"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDUBody, choice.rRCMeasConfig),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCMeasConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rRCMeasConfig"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_XRANCPDUBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellConfigRequest */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cellConfigReport */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uEAdmissionRequest */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uEAdmissionResponse */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* uEAdmissionStatus */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* uEContextUpdate */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* uEReconfigInd */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* uEReleaseInd */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* bearerAdmissionRequest */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* bearerAdmissionResponse */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* bearerAdmissionStatus */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* bearerReleaseInd */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* hORequest */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* hOFailure */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* hOComplete */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* rXSigMeasReport */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* l2MeasConfig */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* radioMeasReportPerUE */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* radioMeasReportPerCell */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* schedMeasReportPerUE */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* schedMeasReportPerCell */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* pDCPMeasReportPerUe */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* uECapabilityEnquiry */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* uECapabilityInfo */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* scellAdd */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* scellAddStatus */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* scellDelete */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 }, /* rRMConfig */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 28, 0, 0 }, /* rRMConfigStatus */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 29, 0, 0 }, /* seNBAdd */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 30, 0, 0 }, /* seNBAddStatus */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 31, 0, 0 }, /* seNBDelete */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 32, 0, 0 }, /* trafficSplitConfig */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 33, 0, 0 }, /* hOCause */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 34, 0, 0 } /* rRCMeasConfig */
};
asn_CHOICE_specifics_t asn_SPC_XRANCPDUBody_specs_1 = {
	sizeof(struct XRANCPDUBody),
	offsetof(struct XRANCPDUBody, _asn_ctx),
	offsetof(struct XRANCPDUBody, present),
	sizeof(((struct XRANCPDUBody *)0)->present),
	asn_MAP_XRANCPDUBody_tag2el_1,
	35,	/* Count of tags in the map */
	0, 0,
	35	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_XRANCPDUBody = {
	"XRANCPDUBody",
	"XRANCPDUBody",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_XRANCPDUBody_constr_1, &asn_PER_type_XRANCPDUBody_constr_1, CHOICE_constraint },
	asn_MBR_XRANCPDUBody_1,
	35,	/* Elements count */
	&asn_SPC_XRANCPDUBody_specs_1	/* Additional specs */
};

