/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_XRANCPDUHdr_H_
#define	_XRANCPDUHdr_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include "XRANC-API-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* XRANCPDUHdr */
typedef struct XRANCPDUHdr {
	UTF8String_t	 ver;
	XRANC_API_ID_t	 api_id;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} XRANCPDUHdr_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_XRANCPDUHdr;
extern asn_SEQUENCE_specifics_t asn_SPC_XRANCPDUHdr_specs_1;
extern asn_TYPE_member_t asn_MBR_XRANCPDUHdr_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _XRANCPDUHdr_H_ */
#include <asn_internal.h>
