/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#include "XRANCPDU.h"

static asn_TYPE_member_t asn_MBR_XRANCPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDU, hdr),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_XRANCPDUHdr,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hdr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct XRANCPDU, body),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_XRANCPDUBody,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"body"
		},
};
static const ber_tlv_tag_t asn_DEF_XRANCPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_XRANCPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* hdr */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* body */
};
static asn_SEQUENCE_specifics_t asn_SPC_XRANCPDU_specs_1 = {
	sizeof(struct XRANCPDU),
	offsetof(struct XRANCPDU, _asn_ctx),
	asn_MAP_XRANCPDU_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_XRANCPDU = {
	"XRANCPDU",
	"XRANCPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_XRANCPDU_tags_1,
	sizeof(asn_DEF_XRANCPDU_tags_1)
		/sizeof(asn_DEF_XRANCPDU_tags_1[0]), /* 1 */
	asn_DEF_XRANCPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_XRANCPDU_tags_1)
		/sizeof(asn_DEF_XRANCPDU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_XRANCPDU_1,
	2,	/* Elements count */
	&asn_SPC_XRANCPDU_specs_1	/* Additional specs */
};

