/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XRAN-PDU"
 * 	found in "../xranc-sb-api/xRAN-API-PDUs.asn1"
 * 	`asn1c -fcompound-names -pdu=XRANCPDU`
 */

#ifndef	_XRANCPDU_H_
#define	_XRANCPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "XRANCPDUHdr.h"
#include "XRANCPDUBody.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* XRANCPDU */
typedef struct XRANCPDU {
	XRANCPDUHdr_t	 hdr;
	XRANCPDUBody_t	 body;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} XRANCPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_XRANCPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _XRANCPDU_H_ */
#include <asn_internal.h>
